### ISSUE TITLE
Fill layers don't respect the canvas dimension on PSD's

### ISSUE THREAD

**Issue by reywright** [avocode/avocode#1000]
Is this normal? By the way this is with the usage of artboards. OS X Capitan

**Comment by scarysnow** [comment]
It appears that the fill layers are rendered to fill the entire document canvas size, as opposed to the specific canvas dimensions of the artboard they are placed in.

**Comment by bolekkerous** [comment]
Unfortunately, Avocode doesn't support Photoshop artboards correctly yet.

There's already a feature request on our UserVoice forum, which can be upvoted, so we know what to prioritize in the future:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/9428469-support-photoshop-artboards

We'd advise to ungroup artboards in the design in the meantime. Once that is done, the design be displayed just fine.

I'll close this issue since it's a duplicate - here's a link to the original issue #374
