### ISSUE TITLE
Designs not showing up, only shows white blank screen

### ISSUE THREAD

**Issue by nayaabkhan** [avocode/avocode#1007]
**Avocode 2.8.4 on Mac OS X El Capitan, not checked on other platforms.**

Designs are not showing up, instead only see white screen. Though on hovering it shows bounding boxes like: https://www.dropbox.com/s/yljji5df2ng6r0n/Screen%20Shot%202016-08-01%20at%203.26.24%20PM.png?dl=0

Thumbnails show fine: https://www.dropbox.com/s/j1i3zfyq2bal0am/Screenshot%202016-08-01%2015.28.19.png?dl=0

**Comment by connor-bean** [comment]
Hello, @nayaabkhan -

This issue is caused by using Sketch 3.9 version with older version of Sketch plugin.

Are you sure you are using the latest Sketch plugin (3.8 version)?

If the result is the same (white layers), please uninstall the plugin, quit Sketch and install the plugin again. After you sync the design again with the new version (it's needed to resync it to see the difference), it should work just fine.

Let me know whether it works!
Best regards,
Connor, Avocode Team

**Comment by nayaabkhan** [comment]
Hey @connor-bean,

I'll check it with the designer who uploaded these screens and be back on this as soon as possible. Thanks for the quick reply!

**Comment by concuria** [comment]
I had the same problem yesterday. I will also ask the designer to uninstall en reinstall the sketch plugin and report whether or not this fixes the issue.

**Comment by concuria** [comment]
Updating the sketch plugin and re-syncing the design solved the issue.

**Comment by nayaabkhan** [comment]
Hey @connor-bean,

You were right! Issue got fixed with the correct plugin version. Closing.
