### ISSUE TITLE
Avocode 2.8.4 sketch sync

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#1013]
Hi after sync with sketch happen this problem. All layers is there but no images.

![image](https://cloud.githubusercontent.com/assets/6084353/17367295/bca02f3e-598f-11e6-824b-145dd2f9ea63.png)

**Comment by connor-bean** [comment]
Hey @vAhyThe -

This issue is caused by using Sketch 3.9 version with older version of Sketch plugin.

Are you sure you are using the latest Sketch plugin (3.8 version)?

If the result is the same (white layers), please uninstall the plugin, quit Sketch and install the plugin again. After you sync the design again with the new version (it's needed to resync it to see the difference), it should work just fine.

Let me know whether it works!
Best regards,
Connor, Avocode Team

**Comment by vAhyThe** [comment]
I will try and i send
 you feedback

**Comment by vAhyThe** [comment]
It works !! thx for help
