### ISSUE TITLE
Sketch Plugin 3.9 is not displaying designs at all

### ISSUE THREAD

**Issue by XVincentX** [avocode/avocode#1014]
Hello!
We have updated Sketch and its plugin for Avocode to 3.9 version.

Since this happened, I am unable to open any design. Basically I get an almost blank screen

![image](https://cloud.githubusercontent.com/assets/1416224/17368644/438bb1d0-5995-11e6-88ee-7a5eaa54f627.png)

...but the elements are there, somewhere, because if I try to select something:

![image](https://cloud.githubusercontent.com/assets/1416224/17368667/53b1a376-5995-11e6-9457-878644bf462c.png)

You can see that I'm able to select the elements.
Is there any update/know issue about that?

Thanks!

**Comment by bolekkerous** [comment]
Hello!
This issue is caused by using Sketch 3.9 version with older version of Sketch plugin.

Are you sure you are using the latest Sketch plugin (3.8 version)?

If the result is the same (white layers), please uninstall the plugin, quit Sketch and install the plugin again. After you sync the design again with the new version (it's needed to resync it to see the difference), it should work just fine.

Let me know whether it works!
Best regards,
Bolek, Avocode Team

**Comment by XVincentX** [comment]
I am not sure how, but it seems like it has been fixed updating Avocode to 2.9.0
I'll verify one more time and post back.
