### ISSUE TITLE
App screens appearing white

### ISSUE THREAD

**Issue by markst** [avocode/avocode#1028]
V.2.9.1

<img width="1440" alt="screen shot 2016-08-08 at 13 50 10" src="https://cloud.githubusercontent.com/assets/274318/17480286/10be22e6-5d6f-11e6-9a50-67a5c5f1d551.png">

**Comment by connor-bean** [comment]
Hello, @markst -

This issue is caused by using Sketch 3.9 version with older version of Sketch plugin.

Are you sure you are using the latest Sketch plugin (3.8 version)?

If the result is the same (white layers), please uninstall the plugin, quit Sketch and install the plugin again. After you sync the design again with the new version (it's needed to resync it to see the difference), it should work just fine.

Let me know whether it works!
Best regards,
Connor, Avocode Team

**Comment by markst** [comment]
@connor-bean I've asked my colleague & will get back to you. cheers

**Comment by markst** [comment]
@connor-bean my colleague is using Avocode sync 3.8 & has resynced the designs, the screen still appear white as attached above. 

![image](https://cloud.githubusercontent.com/assets/274318/17506470/fdd7dd42-5e00-11e6-8649-626e3d71443b.png)

**Comment by markst** [comment]
@connor-bean I installed Sketch & Plugin on a new machine, seems to be all good for now...
