### ISSUE TITLE
I can't open some smartobject inside PSD

### ISSUE THREAD

**Issue by JaroslavBereza** [avocode/avocode#1032]
I can't open some smartobject inside PSD.

Some I can open but other not. Avocode says that layer is rasterized layer instead smart object.

**Comment by vojtatranta** [comment]
Please send us problematic psd at team@avocode.com thank you!

**Comment by jardicc** [comment]
This issue is half year old... I don't remeber which PSD was problematic. :-|

**Comment by bolekkerous** [comment]
This happens when the smart object is imported from Illustrator. Unfortunately, Avocode does not support Illustrator smart objects yet.

If you want us to support Illustrator, please upvote it on our UserVoice:

Illustrator support:
https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6992611-illustrator-support

At least preserving vectors in Illustrator smart objects:
https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/8462584-preserve-vectors-in-a-smart-object-from-illustrato

I'll close this issue and you can follow the progress on the UserVoice issues or here #967

**Comment by jardicc** [comment]
This wasn't illustrator object. I wouldn't expect vector object support from avocode. So I wouldn't start this topic. If I will see this problem again, I will tell you.

Btw: PSD can have three types of vector object. AI, EPS, SVG 

SVG is easy, EPS is dificult and AI should be hardcore.

**Comment by bolekkerous** [comment]
Oh, okay then - however, we're not able to identify the problem properly right now without more information (if it is not Illustrator smart object), so I'll close the issue. If you happen to stumble upon this problem again in the future, please comment here or create a new issue.
