### ISSUE TITLE
Avocode always says "Your Avocode has gone bad" on my Mac

### ISSUE THREAD

**Issue by edge0703** [avocode/avocode#107]
I just installed the Avocode app and synced a Sketch document with 10+ artboards, but whenever I want to inspect the layers of an artboard in the Avocode app I get the error "Your Avocode has gone bad". No matter which artboard I choose. So basically I can't use the App and the whole thing is worthless to me. 

I'm on a Retina iMac with the latest Yosemite installed.

**Comment by edge0703** [comment]
Another problem is that the PNG is not very accurate. The exported images look very pixelated, way worse then when I directly export them from Sketch.

**Comment by tomashanacek** [comment]
Hi, could you share us the problematic design to support@avocode.com? (Ideally through Avocode manager.)

**Comment by petrbrzek** [comment]
@edge0703 I've just tested to export the same image from Sketch and Avocode and they are almost identical. Could you send us the problematic image?

![images](https://cloud.githubusercontent.com/assets/879564/5960560/a23e25b8-a7d6-11e4-963d-e641735192e9.png)

**Comment by edge0703** [comment]
You can have a look at the problematic design at my user christian.krammer@brain.at. 

Also, regarding the exporting of assets: Unfortunately the difference is quite significant. When I export the image in Sketch, it looks like this: https://db.tt/4oQReWjG. And if I export it with Zeplin, it looks like this: https://db.tt/9Ldgp2sv. If you open them both in Photoshop, overlay them and zoom in, then the one from Zeplin has quite jagged lines, the text looks pixelated and also the white text within the orange area has a strange "green" glow around it. And even if you don't zoom in you can purely see the difference.

I would totally understand all of that if you would still be in beta, but since you aim to charge money for your service and you announced that Avocode has been released yesterday my appreciation is limited. 

Also, I wanted to answer to the "welcome mail" from "Vu at Avocode <vu@avocode.com>" yesterday and all I got back was an error message that the address doesn't exist. So I'm a bit grumpy at the moment since I'm in the trial version and I can't see our team using Avocode in the future and we need to fall back to Zeplin and InVision. The former also has it's shortcomings, but at least it mostly works as intended. InVision is great by all means, I love to use it. 

Update: Just wanted to try it out again, but suddenly I can open all of the artboards with no error message anymore. But the problem when exporting assets still exists.

**Comment by petrbrzek** [comment]
I’m co-founder of Avocode and I’d like to respond to Chris Krammer.
We’ve been testing your issue half a day and here are our results:

- It’s not necessary a bug in Avocode. Images are being displayed as we get them from Sketch. In other words, that problem exists in Sketch as well. The main problem is caused by this option

![preferences](https://cloud.githubusercontent.com/assets/879564/5979303/e434c91a-a8a6-11e4-877f-5292801ac04e.png)

- Here is a related excerpt from Bohemian Coding website: 

> “For sub-pixel antialiasing to work, the text has to be drawn on an opaque (colored) background because the system needs to know what the final composited result will look like. This conflicts with layer blending.

> For layer-blending to work correctly, Sketch has to render all layers on a transparent background. That way the layers can blend together as expected and then the final result can be rendered back into Sketch's white canvas.

> So this presents us with a problem; we cannot render subpixel-antialiased fonts without an opaque background, and we cannot accurately render blending with one.”

- Avocode Sketch plugin exports all the layers separately. That’s the reason why it looks different. Can we solve it somehow? There are some ways but neither of them is perfect. For example, we could render real fonts in Avocode but then there is a problem when a developer doesn’t own that font. It’s tough. We’ll definitely try to come up with something.

On the other hand, the need to export font layers as a bitmap (PNG, JPG) is not so frequent use-case. In most cases you just use a font directly in the code (where you cannot ensure how it will look like).

**Comment by edge0703** [comment]
Thanks for your effort Petr!

The things is: Why does it look good (or at least better) if you create the assets via InVision?https://db.tt/y72nkzI8

It's not optimal either, but it looks better than in Avocode. I can't use the text as a separate layer (text with real fonts) here, because I need it for an email newsletter, and it's a Google font probably not installed on many computers.

So, can I do anything that exported images from Avocode look better? I'd still love to use Avocode, but under these circumstances it's hard for me. But as you say, maybe this "everything on one layer" is no frequent use-case, so it may work better if I extract assets separately next time.

**Comment by petrbrzek** [comment]
Hello again Chris,

> “The things is: Why does it look good (or at least better) if you create the assets via InVision?”

It works in a different way. With InVision you have to create all the slices in Sketch app in order to view them on the web.
As you probably know, slices crop defined area thru selected layers so there is no problem with font antialiasing (if a background layer exists).

We’ll probably support real text rendering in Avocode but as I wrote earlier, the developer must own the font (we could fallback to raster).

**Comment by edge0703** [comment]
And wouldn't it be possible to add an option like "Import as flat image"? Because most of the times you may not need the text area itself but the whole thing. Or do I misunderstand something here?

**Comment by petrbrzek** [comment]
We could add some special syntax to Sketch to indicate that you'd like to export a given group of layers as a flat image. For example the plus symbol.

![syntax](https://cloud.githubusercontent.com/assets/879564/6020906/a43234fc-abb1-11e4-996f-7d88603f7bc6.png)

What do you think?

**Comment by edge0703** [comment]
That would be a great idea I think. Thanks for your help!

**Comment by rychlis** [comment]
I've created a feature idea on uservoice to replace this issue: https://avocode.uservoice.com/admin/forums/277080-feature-voting/suggestions/7121386-export-a-given-group-of-sketch-layers-as-a-flat-im
