### ISSUE TITLE
A very handy function has disappeared. It was a selection of lines with automatic copying.

### ISSUE THREAD

**Issue by Souvel** [avocode/avocode#1073]
It was possible to select rows with the mouse and they immediately copied to the clipboard.
But with version 2.10 you can copy only one line by clicking on the number of lines .

**Comment by jakubzitny** [comment]
Hi @Souvel, thanks for letting us know. As a matter of fact, you are not the first one to complain about this. We're already discussing this in issue #1068, so I'll close this one. Since you're not the only one who doesn't like this, we'll think about bringing the old functionality in one of the next releases.

Stay tuned 😉
