### ISSUE TITLE
Not copied to a single css property

### ISSUE THREAD

**Issue by AlexLvov** [avocode/avocode#1085]
Hi! After the upgrade to Avocode 2.10 is not copied to a single css property, a mouse click - http://prntscr.com/ceaap9 .
By the way, how do I load a previous version 2.09?

**Comment by vojtatranta** [comment]
@AlexLvov just click on the line number.

**Comment by AlexLvov** [comment]
Well, in version 2.09, I could select multiple items using the ctrl (eg, 3 out of 5). Your way few can not be selected. How can I highlight a few points?

**Comment by vojtatranta** [comment]
@AlexLvov you can still use your mouse to select lines and then copy lines.

**Comment by vojtatranta** [comment]
@AlexLvov but anyway we will add feature to copy multiple lines you select with `ctrl/cmd` and copy area with `click + shift`

**Comment by AlexLvov** [comment]
In fact of the matter is that I can not. Please give me a link to avocode 2.09

**Comment by AlexLvov** [comment]
In  Avocode 2.09 all worked well

**Comment by jakubzitny** [comment]
Hey @AlexLvov, yeah we know about this. Thanks for your report. This is intentional in `2.10` and there is already a number of people that'd like the old behaviour back. We're already talking about it in #1068. I'll close this one and please look there for more info, for updates and also for the links to download older version of Avocode 😉.

**Comment by AlexLvov** [comment]
thank!
