### ISSUE TITLE
Calculate em's value properly

### ISSUE THREAD

**Issue by vrozkovec** [avocode/avocode#1089]
Example:
  _font-size_: 2.625em;
  _line-height_: 3.125em; <-- wrong
  _line-height_: 1.19em; <-- correct

According to my understanding, once you set font-size to some element, other properties, such as line-height, padding and margin are calculated relatively to the element's font-size property.

That means the value should be recalculated as 3.125 / 2.625 = **1.19em**.
Setting line-height: **3.125em** the line will be three times bigger than font-size.

In px equivalent that would mean:
  _font-size_: 42px;
  _line-height_:  131px <-- wrong
  _line-height_: 50px; <-- correct

Thanks.

**Comment by vojtatranta** [comment]
You are totally right!

We have a bug there. We always pass base font-size value set for whole design and ignore font-size set on individual layer.

This is easy, fix. Thank you!

**Comment by connor-bean** [comment]
We just released 2.11 so I'm closing this out. Please let us know if this problem persists.

You can download the update at https://avocode.com/news.html

Thanks for your patience on this.

Connor, Avocode Support

**Comment by bolekkerous** [comment]
I'm closing this issue since we're not supporting EM's anymore. The reason is that we could not reliably tell you whether EM value of the units is correct. EMs are relative to the font size of parent element or the font-size of the element you set width or height to. So we would be able only to use the base font size on the whole document and the font size of current layer you’ve selected. And that is not quite correct while EMs can be effected by any other font size of any of the parent elements. So we decided to drop support for EMs and rather support just REMs which we can determine exactly.
