### ISSUE TITLE
v2.10.1 Can not upload PSD file 187MB. Linux. EOM

### ISSUE THREAD

**Issue by VadimZhiltsov** [avocode/avocode#1095]
Can not upload PSD file 

OS: Linux
version: 2.10.1
PSD side: 187MB

**Comment by connor-bean** [comment]
Hey @VadimZhiltsov -

We currently have some issues with huge bitmap images in PSD's (most of the times shutterstock images nested in a smart objects - usually with layers that are over 20mpix). Could this be the case? 

I'd recommend to use the Photoshop plugin to sync the design until we fix this issue. You can also ask your designer to resize the resolution of those images or rasterize them. If you do not have access to Photoshop, you can always send the design to us at team@avocode.com and we'll upload it for you as soon as possible.

We're already working on an improved version of rendering, which should fix the problem.

Thanks,
Connor, Avocode Support

**Comment by bolekkerous** [comment]
Hey, this should be hopefully already fixed in the newest versions of Avocode.

Please try to update your app by hitting the "Check for Updates" in menu or by downloading latest version here:

https://avocode.com/download.html

If you still encounter this problem, please comment and I'll reopen this issue.
