### ISSUE TITLE
Color Fills on Artboards bleed into the entirety of the canvas (including on top of other artboards)

### ISSUE THREAD

**Issue by carterdea** [avocode/avocode#1098]
I'm using Photoshop CC 2015 w/ PSDs, I'm uploading them via the Avocode Plugin for Photoshop.

I have color fills on some artboards, and when I upload the PSD to Avocode the color fills go on top of other artboards. My developer has to go into the layers and hide it, it's just a pain.

Wouldn't it make more sense to make the edges of an artboard the bounds like it shows up on Photoshop? (including the Export)

Here is the canvas on Photoshop:
<img width="1030" alt="screen shot 2016-09-10 at 8 36 44 pm" src="https://cloud.githubusercontent.com/assets/803962/18414998/6f298910-7796-11e6-8d3a-d08b1d7d005e.png">

And here it is on Avocode: 
<img width="891" alt="screen shot 2016-09-10 at 8 36 56 pm" src="https://cloud.githubusercontent.com/assets/803962/18414999/73ad282a-7796-11e6-8ec1-1911cafe1288.png">

**Comment by petrbrzek** [comment]
Thanks for reporting the issue. Avocode doesn't support PS artboards well right now. We know about it and want to improve the support in upcoming releases.

**Comment by bolekkerous** [comment]
Apologies for the late reply - unfortunately, Avocode doesn't support Photoshop artboards correctly yet.

There's already a feature request on our UserVoice forum, which can be upvoted, so we know what to prioritize in the future:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/9428469-support-photoshop-artboards

We'd advise to ungroup artboards in the design in the meantime. Once that is done, the design be displayed just fine.

I'll close this issue since it's a duplicate - here's a link to the original issue #374
