### ISSUE TITLE
Feature proposal: show distance in em, relatively to the first element selected

### ISSUE THREAD

**Issue by vrozkovec** [avocode/avocode#1108]
When working with responsive design and using em units, it would be nice if also distances are shown in em, in relation to the first selected element.
Don't know how that would work UI-wise, just when working on my last design, I've done many calculations to get proper em margin / padding value. 
Also keep in mind how em values are calculated: #1089

**Comment by vojtatranta** [comment]
EM units are not quite good to use, since they are affected by `font-size` of any of parent elements, so we cannot reliably say size in EMs only from "base font size". And rather then giving inaccurate that we do not support such feature.

A better idea is to use REMs unit, as they are relative to document `font-size`. And we are about to add such feature.

Closing this issue.
