### ISSUE TITLE
Incorrect code generation

### ISSUE THREAD

**Issue by PhantomOfTheOpera** [avocode/avocode#1119]
Just look at screensho, two last line about fonts. Obviously, they are rather strange.  Nothing serious, but could be fixed in come way
![screenshot from 2016-09-20 20-50-55](https://cloud.githubusercontent.com/assets/16744898/18682265/3b7c26a0-7f74-11e6-843d-85cf387eb66f.png)

**Comment by jakubzitny** [comment]
Hi @PhantomOfTheOpera, thanks for the report.

In your design, the dash (`-`) character has `Arial` font. Maybe it's because the `Intro` font does not support dash (which would be weird) or your designer used Arial on purpose.

We handle these cases exactly as you can see in the code panel.
The first line `font-family: Intro;` is for the text without the dash and the Arial is for dash only.

There is probably no better solution for such cases. As a developer you probably have to split it into classes manually.

I am going to close this issue as this is actually correct. If you have a better tip for how to handle these cases or any other tips or problems with Avocode, feel free to let us know.

**Comment by PhantomOfTheOpera** [comment]
@jakubzitny
Let me try:
Some facts:
1) 99% the Arial font-family string would be deleted this case.
2) You (as an avocode developer) are able to separate main font-family from second(by main here, I mean font-family, which is used more. Just count(sample) number of symbols in Intro font, and Arial, then decide.
How do I see it:
Just leave 'font-family: Arial' commented
This has next pluses:
1) I'll know that font doesn't Support such a symbol(s)
// Thank's god, I'm programmer, I don't care of that:)
2) I am not going to do another redacting(deleting or so).
Thank's)
Sorry for my English. Afraid, it's awfull

**Comment by jakubzitny** [comment]
Yes, that would be an option, but I don't think it would be a lot better than the current one. You already have the info about the characters in the comments, so probably you will just copy the first line with `Intro` font. When you put it into your code and look into the browser you'll probably see that the dash is not exactly the same as in the PSD design. In that case you can fallback to `Arial` for the dash or just leave it like that.

We have similar behavior for when you select multiple layers. Everything is in the code panel and you have to split it in your code manually.

You can also check `Selector` setting in `Preferences -> CODE` and you will have it automatically in separate CSS classes.
