### ISSUE TITLE
Style to CSS. Wrong color code

### ISSUE THREAD

**Issue by aivaras-b** [avocode/avocode#1129]
Selected element generated CSS code shows wrong color code while double checking it with color picker shows right one.
![wrong_color](https://cloud.githubusercontent.com/assets/17545646/18825700/6c643e44-83d2-11e6-873b-170906389da5.png)

**Comment by bolekkerous** [comment]
Hello, Aivaras!
Could you please share the problematic design with us at team@avocode.com, so we can investigate the issue properly? Please reference the issue number #1129 in the e-mail.

Thanks!
Best regards,
Bolek, Avocode Team

**Comment by connor-bean** [comment]
Hello, Aivaras!
Could you please share the problematic design with us at team@avocode.com, so we can investigate the issue properly? Please reference the issue number #1129 in the e-mail.

Thanks!
Connor, Avocode Support

**Comment by vojtatranta** [comment]
@aivaras-b 
This may be caused by color scheme in source PSD or Sketch files.

Basically, if you pick a color in Avocode from the document, Avocode just takes the color that is "on the screen", but this depends on selected color scheme in Photoshop.

Here is more info to this topic, along with guidelines how to set color scheme properly in Photoshop. #1019 

I mark this as a duplicate.
