### ISSUE TITLE
Feature request: import variables

### ISSUE THREAD

**Issue by JayCarney** [avocode/avocode#1134]
I keep having problems with projects dropping variables that have been created. This has mostly gone away, but there are still edge cases that cause it (updating to the newest version of the app today caused the latest case)

I was thinking that having import functionality to take variables that have been added to a project previously, and re-add them to the Avocode app would help mitigate this

**Comment by greystate** [comment]
This is the only thing that drives me absolutely crazy :-) I spend quite some time adding variables and replacements, but there's only so many times you want to bother getting that RegEx correct, only to have it disappear into thin air with the next update...

Please consider _some way_ of fixing this - be it an export/import option or anything else you can come up with.

Thanks!

**Comment by vojtatranta** [comment]
Hi all,
well, we tried really really hard to reproduce such error. I even updated from the ancient versions of Avocode to newer ones and still no luck at all. Could you please one of you confirm that it still happens in newer versions?

Please reopen this again if it still happening. Anyway we plan to add exporting of variables to json so that you could store it in git and share it among the devs.
