### ISSUE TITLE
Large Sketch file hangs...

### ISSUE THREAD

**Issue by JoeDawson** [avocode/avocode#1179]
Hello,

I'm attempting to share a pretty large Sketch file (~610mb) with a colleague and I'm having issues trying to sync the file with Avocode.

Some artboards have uploaded file, but some artboards just aren't (at least from what I can see) doing anything at all. I've attempted to sync a single artboard throughout the entire day with no luck.

One attempt I waited 3 hours, no movement at all with the progress bar and Avocode shows a missing image when trying to access.

I've also tried creating a completely new Avocode project to try and sync to but unfortunately still no luck, it just hangs.

Any ideas?

**Comment by JoeDawson** [comment]
I think it's worth nothing I'm using **Sketch 40.3** and **Avocode Sync 3.9**.

**Comment by danielgeri** [comment]
Wondering if my issue (https://github.com/avocode/avocode/issues/1180) is related

**Comment by bolekkerous** [comment]
Hey!

It looks like an issue we've seen a few times before. It may be happening because the design is too huge. Because of that, the plugin isn't able to retrieve correctly all the layer data (because there are too many layers and the RAM can't handle the load). It should help to split the design into smaller parts.

We do understand it is not a perfect workaround, but I'm afraid it's the only way I am aware of right now. One another thing that could help is to combine path layers which are going to be exported as a one layer with Layer -> Combine -> Union - this will create a single layer out of them that should export quicker.

However, it is possible that the cause is somewhere else. It would help us a lot if you could send us the problematic design to team@avocode.com so we can have a proper look.

We do apologize for the inconvenience.
Best regards,
Bolek, Avocode Team

**Comment by JoeDawson** [comment]
Hey @bolekkerous,

Would this apply to a single artboard? We have artboards for Desktop, Tablet & Mobile for a few pages in a web project designed.

Some of them have synced fine (mobile designs) but the larger ones are the ones that seem to be struggling.

You also mention that RAM could be an issue, is that client side (my RAM) or are you referring to your servers RAM?

Thanks

**Comment by bolekkerous** [comment]
Hey, @JoeDawson,

yes, that sounds like this could be the issue with the larger artboards. Is it possible that the artboards that are not syncing have some group of layers with a lot of vectors/layers? It could help to combine the path layers which are going to be exported as one layer with Layer -> Combine -> Union - this will create a single layer out of them that should be uploaded correctly.

In this case we're referring to the client side RAM - the plugin processes the design locally to our format and then upload it to our servers, so if the design is too large or has too many layers, the local machine may not be able to handle processing all the layers.

The last thing that should always work is to try splitting the design to  a few smaller ones to see whether that's the reason of the problem.

Does it help at least a little? 
Best regards,
Bolek, Avocode Team
