### ISSUE TITLE
No Document Open

### ISSUE THREAD

**Issue by pierocortex** [avocode/avocode#1234]
Dont know why, but suddenly my Avocode Sketch plugin has stopped working, will not recognise that a document is open, no matter what i do. I am running up to date Sketch, plugin and macOS. PLease
![screen shot 2017-01-10 at 12 50 16](https://cloud.githubusercontent.com/assets/25032390/21806921/079d5008-d734-11e6-81ba-95384f664d7c.png)
 help!

**Comment by connor-bean** [comment]
Hey @pierocortex -

We've encountered this problem before - it was caused by having Sketch named differently than "Sketch". Could you please double check whether the name of the Sketch application you're using is "Sketch"? Sometimes, it may be something like "Sketch 2", and that may cause the problem.

Let me know whether it helps!
Best regards,
Connor, Avocode Team

**Comment by pierocortex** [comment]
Hey Connor, the Sketch app in my file is named "Sketch 3" would changing this help? Thanks for your quick response

**Comment by connor-bean** [comment]
Hey @pierocortex -

Yeah that sounds like the problem. Change the name to just "Sketch" and let me know if that helps or not. 

Thanks!
Connor, Avocode Support

**Comment by pierocortex** [comment]
It most certainly has. Worked straight away. This saves me a lot of pain today! Thanks

**Comment by connor-bean** [comment]
Great news! Please let us know of any other questions in the future.

Connor, Avocode Support
