### ISSUE TITLE
Sketch Symbol instances won't export correctly to SVG

### ISSUE THREAD

**Issue by callumacrae** [avocode/avocode#1239]
Sometimes I get the following output:

```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Avocode 0.4.0 - http://avocode.com -->
<svg height="NaN" width="NaN" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 NaN NaN">
    <image xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVQYV2NgYAAAAAMAAWgmWQ0AAAAASUVORK5CYII=" height="26" width="76" y="0" x="-1" />
</svg>
```

(that's the google logo)

It looks like it happens when there's only only later and it's an `<image>` - the width and height are NaN.

**Comment by rychlis** [comment]
Hey, thanks for the report! Does this error happen for a specific layer or randomly?

Also what version of Avocode are you using?

**Comment by callumacrae** [comment]
Happens for a few specific layers. I'll see if I can get a document to replicate it in.

Using 2.12.3 - will update and try again.

**Comment by rychlis** [comment]
OK. It would help us a lot if you could send us such document. You can send the file to our support email team@avocode.com if you don't want to upload it publicly here at github

Thanks!

**Comment by callumacrae** [comment]
Sketch file (GitHub doesn't allow Sketch file uploads 😞): [Test.zip](https://github.com/avocode/avocode/files/711574/Test.zip)

Avocode: https://manager.avocode.com/view/220ccb328b8f4880a20f5ad90ec946a8/

Trying to export the google layer results in a broken SVG, for me.

**Comment by rychlis** [comment]
Thanks a lot for the document, we are now able to reproduce the issue :)

The problem happens when exporting symbol instances in sketch documents, we will try to fix the issue in the upcoming release. In the meanwhile as a workaround you can export the SVG by opening the Symbol definition (by double-clicking the layer, the symbol definition Artboard must be synced by Avocode Plugin) and export all the layers there - the "Google" layer group in this case:

![google-group](https://cloud.githubusercontent.com/assets/1819747/22030827/33a091be-dcdf-11e6-8847-29830663c7eb.png)
](url)

**Comment by callumacrae** [comment]
amazing, thanks!

**Comment by jakubzitny** [comment]
Hi guys. Symbol instances should be finally exportable to SVGs correctly in `2.16.0`, please update and let us know if you have any other problems with Avocode 😉 

Please note, that since the symbol overrides are not inspectable in Avocode yet, the contents of SVG will be bitmap, not vector.

We're working hard on bringing the ability to inspect symbols with overrides in-place inside the document though and it should be ready soon. For now, please vote for the feature on our [UserVoice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/17982586-nested-symbols-this-needs-to-be-addressed).
