### ISSUE TITLE
Can't delete notes

### ISSUE THREAD

**Issue by miguelmich** [avocode/avocode#1271]
![image](https://cloud.githubusercontent.com/assets/662930/22391824/9859214a-e4c1-11e6-8474-4cccfdf06d01.png)

This is the third time in this month we have connectivity problems with this App :-1:

**Comment by vojtatranta** [comment]
@miguelmich I am sorry to hear this.

But in general, app doesn't do much with the connection. It just receives connection from the OS. No magic is happening there.

We had an outage during the last week caused by a problem with connection on our backend but that lasted few minutes.

I gues that deleting now works as expected, right? And what do mean by "this is the third time in thie month we have connectivity problems". Do you mean that you are not able to eg. delete notes frequently, or? THanks

**Comment by miguelmich** [comment]
Hello, 

Yes, it's working now, we had several different issues related to connectivity e.g. not being able to log in, creating notes and syncing designs.

**Comment by vojtatranta** [comment]
@miguelmich I apologize for that. We are aware of this and we will for example rework our design downloading logic in order to improve this.

Thank you for your time and reports.

**Comment by miguelmich** [comment]
Thanks a lot, that would be great :)
