### ISSUE TITLE
support rgba

### ISSUE THREAD

**Issue by linedotwww** [avocode/avocode#1287]
could you add support for rgba. And that patients are not comfortable

![1486725718479](https://cloud.githubusercontent.com/assets/15665678/22825206/e502d42e-ef9c-11e6-8251-d4b59679d222.jpg)

background: rgba(131,151,193, .77); 
It's very good))) Sorry for my english

**Comment by vojtatranta** [comment]
@linedotwww sure we support RGBa already, but in this case, your designer made a kinda shortcut - hew created a layer and filled it with color and on this whole layer he applied opacity to 70%. Avocode recognises transparency correctly when effect "solid fill" is used, which is good practice for coloring layers with some opacity. So if your designer set solid fill effect with color and opacity to 70%, you'd get desired `rgba(131,151,193, .77)`

Because now Avocode simply shows what designer did - filled manually layer with color and then applied opacity on the whole layer.
