### ISSUE TITLE
issues uploading

### ISSUE THREAD

**Issue by ninjamonkno1** [avocode/avocode#1313]
I am having issues uploading files. When I drag a bunch of files across from finder it is not uploading all of them. 

for instance I just dragged 4 over and it only uploaded 3 of them. 

Also another annoying issue is I am getting PSD's stuck in the assigning state and not uploading. 

An aside, I do not like having to put this stuff on github in a public forum, I would understand if it was an open source project but when I am paying for a product I expect some privacy.

**Comment by bolekkerous** [comment]
Hello -
we apologize for the inconvenience.

If you don't want to discuss this further publicly, we can switch over to e-mail. You can always contact our support at team@avocode.com.

If not - are you able to reproduce the issues with less file uploaded than dragged over? Or is it an issue that's happening randomly from time to time?

About the issues with assigning - same question - is there a way you can reproduce this all the time? Otherwise we would need you to let us know once it happens, so we can investigate properly.

**Comment by ninjamonkno1** [comment]
No worries, I will use that next time ;) 

I can replicate it via opening the dialog and importing that way too. 

I just grabbed 5 files and it processed 4.

**Comment by ninjamonkno1** [comment]
The assigning issue is intermittent but I have one currently stuck in that state if you wish to look at it. 

File is called Suppliers-01.psd

**Comment by bolekkerous** [comment]
You're right, we can reproduce it now. We'll look into that.

**Comment by bolekkerous** [comment]
This should be fixed in 2.13. Your app should update automatically. If it doesn't, you can always download the latest version here:
https://manager.avocode.com/downloads/

If you still experience this issue, please comment here and we'll reopen the issue.
