### ISSUE TITLE
Color mismatch of objects in design view

### ISSUE THREAD

**Issue by VaclovasV** [avocode/avocode#1376]
2.13.4

Desktop

Windows 8

There is color mismatch in avocode, avocode displays colors incorrectly. 
![image](https://cloud.githubusercontent.com/assets/3501072/24906317/ed70597c-1ebf-11e7-8b78-593cfab1e680.png)
Even integrated color picker, sees different color in design (correct is displayed in code panel).
Making screenshot and checking color in photoshop - color is incorrect.
Exporting image from avocode and checking color with photoshop - color is correct.

Can you help with this, because issue is very irritating.

**Comment by bolekkerous** [comment]
Hey, @VaclovasV - 
could you please check what color space is being used in the design? We do support only sRGB color space.

It would also help us if you could send us the problematic design (or just the problematic part), so we can take a closer look at the issue.

Thanks and sorry for the inconvenience.

**Comment by VaclovasV** [comment]
@bolekkerous, color space in which app? This is sketch file and RGB colors are used.

**Comment by bolekkerous** [comment]
Oh okay, it's a Sketch file. Then, could you please send us the design or just it's problematic part to team@avocode.com, so we can investigate the problem? It would help us a lot in pinpointing the problem.

**Comment by VaclovasV** [comment]
@bolekkerous, maybe this is related?
http://graphicdesign.stackexchange.com/questions/53073/color-mismatching-on-sketch-exports

**Comment by bolekkerous** [comment]
Might be, I added it to our internal bug tracking system and our product team should take a look at it soon. Thanks for sending us the file, we'll let you know once we know more.

**Comment by asyla** [comment]
The same issue here. 
Avocode shows incorrect color. Imported from Sketch as well.

![image](https://cloud.githubusercontent.com/assets/14801014/26488007/731c1fa8-420a-11e7-802c-d34ce65ddef9.png)

**Comment by mwq27** [comment]
This is still happening with a Sketch file and Avocode 2.16.2. Is anyone still seeing this issue other than my team?

**Comment by bolekkerous** [comment]
Hey, @mwq27 -
please send us the problematic design to team@avocode.com so we can investigate the problem properly.

This problem is usually caused by color profiles - it's a really complex issue which we're not able to solve on our side with the current technology.

However we're already working on a new rendering technology which should also solve this problem in the end. We aim to release it at the beginning of 2018.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. It was caused by color profiles, which should be ignored with the new rendering engine.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
