### ISSUE TITLE
Unable to import 2x (or more) size images

### ISSUE THREAD

**Issue by insomniaOk** [avocode/avocode#1378]
* **Version**: 2.13.4

* **Web/Desktop**: Desktop

* **Platform**:  Linux

It is impossible to export an image in 2x or more size in a good quality directly from the design (screenshot http://joxi.ru/brRewqOcjGMnA1) You always need to open an image with double click and save it in original size only (screenshot http://joxi.ru/E2pea75cW0bLAY). And also you lose the photoshop filters by this saving.

**Comment by bolekkerous** [comment]
Hey - 
at the moment, we're only able to export vector shapes at @2x+ resolution, because we don't have the data for exporting bitmap images at larger scales.

We should be able to export even bitmap images at larger scales (if the source is at sufficient resolution) in the future, once we implement new processing and rendering architecture, which is in development for some time and should be finished soon.

If you would like us to be able to export even bitmap images at scale, please upvote this feature request on our UserVoice:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/14576004-export-bitmap-images-2x-3x-4x

**Comment by bolekkerous** [comment]
This should already work as long as the base image is in a high enough resolution.
