### ISSUE TITLE
Processing failed. Can't upload any PSD.

### ISSUE THREAD

**Issue by ffiona** [avocode/avocode#1387]
* **Version**: 2.13.4 and 2.13.5

* **Web/Desktop**: Web and Desktop

* **Platform**: Ubuntu 14.04

Never got a chance to upload files. The image was uploaded successfully (100%) and then processing got 0% and this error.

Console error:

`(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.`

**Comment by bolekkerous** [comment]
Hey, @ffiona -
there was a problem that should be already fixed by our CTO, however because of the problem, there's now a queue for processing of designs. The system should be already stabilizing and as far as I know, it should be back to normal in a short while.

I'll let you know once the backlog is complete and if your upload fails even after that, we'll investigate further.

**Comment by ffiona** [comment]
@bolekkerous  thank you for reply and letting us know about the problem. Hope it'll be fixed pretty soon.

**Comment by bolekkerous** [comment]
The problem should now be fixed and queue completed - it should be possible to upload designs as usual.

Let us know in case of any problems with that.
