### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by jaykobo** [avocode/avocode#1388]
* **Version**: 2.13.5

* **Web/Desktop**: Desktop

* **Platform**: mac OS Sierra Version 10.12.1

Multiple PSD file import failed.

**Comment by bolekkerous** [comment]
Hey,
there was a problem that should be already fixed by our backend team, however because of the problem, there's now a queue for processing of designs. The system should be already stabilizing and as far as I know, it should be back to normal in a short while.

I'll let you know once the backlog is complete and if your upload fails even after that, we'll investigate further.

**Comment by bolekkerous** [comment]
The problem should now be fixed and queue completed - it should be possible to upload designs as usual.

Let us know in case of any problems with that.

**Comment by jaykobo** [comment]
Great, thanks for your answer.
