### ISSUE TITLE
Sketch long load

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#1429]
* **Version**: 

* **Web/Desktop**:

* **Platform**: 

https://upx.cz/iuG

**Comment by bolekkerous** [comment]
Hello!

It looks like an issue we've seen a few times before. It may be happening because there are too many layers in the design. Because of that, the plugin isn't able to retrieve correctly all the layer data (because there are too many layers and the RAM can't handle the load). 

You can combine path layers which are going to be exported as a one layer with Layer -> Combine -> Union - this will create a single layer out of them that should export quicker. In your case, you can create one combined shape from each of the loaders.

We do apologize for the inconvenience - once we have new processing and parsing architecture up and running, this should be no longer a problem. I'll close this as duplicate since we're tracking this issue in #859 

Best regards,
Bolek, Avocode Team
