### ISSUE TITLE
Couldnt  upload designs from Sketch to Avocode

### ISSUE THREAD

**Issue by rihbim** [avocode/avocode#1503]
2.14.4

* **Version**: 

* **Desktop**:

* **MacOS**: 

Sketch plugin

I installed plugin Avocode on my MacOS. And I couldnt upload designs to Avocode from Sketch. 
I made screen of problem - http://prntscr.com/fq22cx

**Comment by jakubzitny** [comment]
Hi @rihbim, thanks for letting us know. You seem to be still using the old plugin. The new one is described at [help.avocode.com](https://help.avocode.com/projects-and-designs/design-upload/upload-sketch-designs-via-avocode-sketch-plugin). Which macOS version are you using, please?

The new plugin should be automatically installed when you launched `2.14.4`. It it's not the case, please remove the old one manually and launch the app again (so it's automatically installed again). There might be some issues with the installation, which is why you stayed stuck with the old one.

We're working on another update `2.14.5` which should be ready early next week and it should fixx the installation issues. In the meantime please let us know if you're able to launch the new plugin and snyc some files.

**Comment by rihbim** [comment]
Thanks for your fast reply

But I have 1 more problem. 

When I uploaded Sketch to Avocode, designs disappear in Avocode after 15-20 min.

What can we do with this problem?

**Comment by jakubzitny** [comment]
Hi @rihbim, does the disappearing happen during the upload or after everything is uploaded? If it's during the upload, I am already working on a fix that will be include in next patch version `2.14.5`.

**Comment by rihbim** [comment]
This problem is still urgent
We cant upload design from Sketch to Avocode.
Problems with the load almost never happen in just 30-40 minutes, designs disappear

**Comment by jakubzitny** [comment]
Can you please send the sketch file to us, so we have a closer look at it? Is it happening to one particular Sketch file or all? Have you tried uploading not all artboards at once, but only some of them? Does that work, please?

**Comment by rihbim** [comment]
Ok
I will send sketch file to your mail
Yes, we tried upload just 1 artboard, but it doesnt changed :(

**Comment by rihbim** [comment]
​
 Layout_20_6_final-1.sketch
<https://drive.google.com/file/d/0B-nEnHKCqnx2TXAzSWhqcW1RQ1U/view?usp=drive_web>
​ for example

2017-07-04 18:16 GMT+03:00 Jakub Žitný <notifications@github.com>:

**Comment by jakubzitny** [comment]
Thanks, I will have a look at it.

**Comment by rihbim** [comment]
Thanks
I sent it to your mail

**Comment by jakubzitny** [comment]
Hi @rihbim, we've just released an update `2.14.5` with a bunch of fixes for Sketch upload. Our support team has uploaded the designs for you and everything worked on our side, so I believe it should work for as well.

Please update your app and let us know if you have any more problems 😉
