### ISSUE TITLE
Project manager didn't show all sketch artboards

### ISSUE THREAD

**Issue by evanre** [avocode/avocode#1547]
* **Version**: 2.14.7
* **Web/Desktop**: Desktop
* **Platform**: Windows 10 x64

Hi, I'm not sure when this issue happened. But today after updating on new version I find out that the project manager didn't show all artboards in sketch project. When I opening some general design and clicking on some smaller part (header or navigation), it opens and all works great. But I can't find this part directly in project manager. It's a big problem for me, because there is small parts that shows only different element state and not linked inside of bigger designs.

PS. About a week ago I've worked with this project and things were good.

<a href="https://ibb.co/mjWax5"><img src="https://thumb.ibb.co/mjWax5/2017_07_24_23_56_28.png" alt="2017_07_24_23_56_28" border="0"></a>

**Comment by jakubzitny** [comment]
Hi @evanre, the smaller parts (header or navigation) are symbols in your design and we've decided to hide the symbols in tha latest version of Avocode. A lot of users were complaining about plenty of artboards in a project, making it difficult to navigate and find specific artboards.

So, for now, you can either downgrade to earlier version if this is really important to you, or just open the symbols from the design as you mentioned.

But don't worry, we're preparing all new organization for Sketch files in the project manager in Avocode `2.15` which should be ready in few weeks. I'll keep this issue open and we'll let you know when it's ready.

**Comment by evanre** [comment]
> we've decided to hide the symbols in tha latest version
That's pretty weird decision. My designer provides me a lot of examples with different element states. Now i need to downgrade the Avocode to see them. You could add some checkbox or something, I don't know. But not to hide them...

**Comment by jakubzitny** [comment]
Yeah, I understand you. However, we really had many requests to get rid of the symbols and we wanted to make a quick release with it to satisfy users. You can download the previous version [here](https://media.avocode.com/download/avocode-app/2.14.6/Avocode%20Setup%202.14.6.exe) and in the meantime we will be trying to fix it in the best possible way.

Also, I am not really sure you know about it, but we have a web avocode in beta version and we're working on the last details to officially release it. The symbols are displayed in the web version, maybe you can use that instead of migrating to the older desktop version. You can find it at [app.avocode.com](https://app.avocode.com/), we support only Chrome browser for now.

**Comment by evanre** [comment]
@jakubzitny Thank you. As temporary solution I've asked designer to create separate artboard with all symbols in project. It works for me. Now the problem is solved.

**Comment by jakubzitny** [comment]
Hi there, there is a new UI for Sketch files in latest Avocode `2.15.0`. Symbols are displayed in a separate page now. You can download it from [avocode.com/download](https://avocode.com/download) or use auto-update to install it. Please give it a try and let us know if you have any more issues.
