### ISSUE TITLE
I can't export to svg. 

### ISSUE THREAD

**Issue by hilashtram** [avocode/avocode#1577]
* **Version**: 
2.14.8

* **Web/Desktop**:
Desktop 

* **Platform**: 
Sierra 10.12.5

i can't open smart object from illustrator in avocode.

**Comment by connor-bean** [comment]
Hello @hilashtram -

Unfortunately we do not support imported smart objects from Illustrator - since the format is different, we're not able to get the vector data from the smart objects at the moment, that's why it's rasterized and can't be exported as SVG. 
​
We're planning to support Illustrator in the future, so please upvote it on our UserVoice: 
https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6992611-illustrator-support
