### ISSUE TITLE
PSDs not displaying correctly in app

### ISSUE THREAD

**Issue by nmessier718** [avocode/avocode#1578]
![unknown-1](https://user-images.githubusercontent.com/20954520/29123171-d4d637d4-7ce2-11e7-806a-4bd1d7c45c52.png)
![unknown-2](https://user-images.githubusercontent.com/20954520/29123172-d4db25be-7ce2-11e7-8c8b-69fd45b94e57.png)
![unknown-3](https://user-images.githubusercontent.com/20954520/29123170-d4d5c1b4-7ce2-11e7-8b6e-1721d324ae73.png)
![unknown-4](https://user-images.githubusercontent.com/20954520/29123168-d4d2c4e6-7ce2-11e7-8054-8130985fdec0.png)
![unknown](https://user-images.githubusercontent.com/20954520/29123169-d4d5300a-7ce2-11e7-9e37-c8d4c3041a45.png)

* **Version**: 

* **Web/Desktop**:

* **Platform**: 

Preview on website looks fine but when opening in app the PSDs are not loading correctly. Images are partially showing, background colors and transparencies half show or are completely missing. Developers can not use these files.

**Comment by connor-bean** [comment]
Hey @nmessier718 -

This looks like an issue caused by using Photoshop artboards in the PSD. Sorry for the confusion - we actually do not officially support Photoshop Artboards at the moment.

Ungrouping the artboards or making a few smaller files containing just one of the artboards (ungrouped though) should fix the problems.

If you want us to support Photoshop Artboards, please upvote it on our UserVoice:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/9428469-support-photoshop-artboards

Best regards,
Connor, Avocode Team
