### ISSUE TITLE
Bug with Avocode

### ISSUE THREAD

**Issue by LKIkost** [avocode/avocode#1590]
* **Version**: 2.14.8

* **Web/Desktop**:Desktop

* **Platform**: Ubuntu 16.04

**Comment by jakubzitny** [comment]
Hey, @LKIkost -
could you please elaborate what exactly happened? And what did you do before it happened?

Thanks and sorry for the inconvenience!

**Comment by LKIkost** [comment]
Hi, i just put psd file to upload in Avacode.17:58, 24 августа 2017 г., "Jakub Žitný" <notifications@github.com>:Hey, @LKIkost -
could you please elaborate what exactly happened? And what did you do before it happened?
Thanks and sorry for the inconvenience!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by jakubzitny** [comment]
Is this happening all the time or only once? Are you able to upload a file at all? When exactly does it happen during the PSD file drag and drop. Does the upload start? Or it just crashes automatically? Can you please try uploading it manually by clicking on `ADD DESIGN` in a project and choosing the file from file system? Maybe the issue here is only with drag and drop here.

**Comment by connor-bean** [comment]
Is this happening all the time or only once? Are you able to upload a file at all? When exactly does it happen during the PSD file drag and drop. Does the upload start? Or it just crashes automatically? Can you please try uploading it manually by clicking on ADD DESIGN in a project and choosing the file from file system? Maybe the issue here is only with drag and drop here.
