### ISSUE TITLE
Change account passwod

### ISSUE THREAD

**Issue by kirillDanshin** [avocode/avocode#1594]
* **Version**: 
2.14.8

* **Web/Desktop**:
web and desktop

* **Platform**: 
linux amd64 (latest fedora)

so - how I can change my account's password?

**Comment by connor-bean** [comment]
hey @kirillDanshin -

You can change your password if you go to app.avocode.com and then go into your Personal Settings (click the avatar in the top right corner of the screen). You can change your password there.

Otherwise, you can also use the Forgot Password link when logging in to the application. It will send you an email to reset it.
