### ISSUE TITLE
After a while in the standby mode, the program closes

### ISSUE THREAD

**Issue by Pavlo-Minkievych** [avocode/avocode#1624]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.15.2`

**Comment by Pavlo-Minkievych** [comment]
After a while in the standby mode, the program closes

**Comment by jakubzitny** [comment]
Hey @Pavlo-Minkievych, is this happening all the time or just once? You have sierra, right?

**Comment by Pavlo-Minkievych** [comment]
Occurs constantly, plus there was a problem after every download of the design you need to completely exit the program otherwise all subsequent downloads are executed with an error.
Sierra 10.12.6

> 15 сент. 2017 г., в 14:54, Jakub Žitný <notifications@github.com> написал(а):
> 
> Hey @Pavlo-Minkievych <https://github.com/pavlo-minkievych>, is this happening all the time or just once? You have sierra, right?

**Comment by jakubzitny** [comment]
Hi @Pavlo-Minkievych, we're trying to reproduce this issue with standby crashing and we cannot really do it. We also have Sierra `10.12.6`, is there any chance you have any unusual Mac set up? How about hardware specs?

Another possible problem (on our side of course) might be that you have quite a lot of designs in Avocode and this might be causing some memory issues that are reflected in the network problems that you had before and also in the issues with sleep or download.

What is the size of you `~/.avocode` data? You can check it by running the following command in Terminal.
```
du -sh ~/.avocode
```

Could you please also try the following?
1) log out and close the app
2) back up the `~/.avocode/` folder (e.g. move it to `~/.avocode-old`)
3) open the app, login and try working with it for a while

Also if this doesn't help with the issues you're having, if you find some time, could you try the first two steps and instead of the third step — open the app, register new trial account and try uploading some of your files and work with Avocode for a while too?

**Comment by Pavlo-Minkievych** [comment]
the problem was disappearing
