### ISSUE TITLE
vector shapes are rendered larger in Avocode than in Photoshop.

### ISSUE THREAD

**Issue by olaf-mangodesign** [avocode/avocode#1650]
* **Version**: 2.15.5

* **Web/Desktop**: both

* **Platform/Browser**: MacOS 10.12.6 & Windows 10, Safari 11.0

Vector shapes created in Photoshop are rendered and measured 2-3 Pixel larger in Avocode than in Photoshop, e.g. a square with 100x100 pixels in Photoshop is shown as 102x102 pixels in Avocode. The vector shapes have no outline and no effects attached. 
[test-vector.psd.zip](https://github.com/avocode/avocode/files/1344582/test-vector.psd.zip)

Some of the older uploaded files show the same behaviour, but not all of our old files. So it could be a problem with the latest Adobe CC update in combination with Avocode.

**Comment by i-v-k** [comment]
Same problem

* **Web/Desktop**: Desktop

* **Platform**: win32 (win10 64bit)

**Comment by bolekkerous** [comment]
Hey,

we’ve just fixed this for newly uploaded designs, so to get rid of this problem, please reupload any design that is affected.

We will be also implementing a solution that will fix it even for already uploaded designs, but that will take some time since it’s quite complex.

So in the meanwhile it is possible to fix it by uploading the designs again. 

Thanks for the patience and sorry for the inconvenience.
