### ISSUE TITLE
Font information bug

### ISSUE THREAD

**Issue by larxenne** [avocode/avocode#1697]
* **Version**: 2.16.1

* **Web/Desktop**: I tryed on both of them, I'm having the same issue

* **Platform/Browser**: Linux / Chrome

* **Avocode e-mail**:  vendor@budafony.com

Hello, I'm having this annoying issue using avocode.
With some psd I'm receiving, the font information is not relevant.

For each text, I'm having the same result:
font-family: "Myriad Pro";
font-size: 12px;

I guess they are the default values.
I asked, and theese psd are made with: photoshop cc 2017

Cheers

**Comment by bolekkerous** [comment]
Hey, thanks for the report.

We figured out that this is caused by a feature of Photoshop that we're not actually supporting on our end yet - predefined Paragraph Styles.

We'll work on supporting this type of workflow as soon as possible.

In the meanwhile, it should be possible to use Character Styles instead, these should work.

**Comment by larxenne** [comment]
Ok, thanks for the answer.
I'm waiting to see this feature comming then :)

Cheers

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. 

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
