### ISSUE TITLE
wrong background color

### ISSUE THREAD

**Issue by orhar** [avocode/avocode#1716]
* **2.16.2**: 

* **Desktop**:

* **windows 10**:

The background color generated by Avocode is incorrect. 
attached screenshot:
![capture](https://user-images.githubusercontent.com/7655339/32316537-49d81fc0-bfb9-11e7-93c7-42c6041224f0.PNG)

**Comment by bolekkerous** [comment]
Hey - 
could you please send us the problematic PSD/Sketch file to team@avocode.com, so we can investigate further?

Thanks!

**Comment by orhar** [comment]
​
 2.psd
<https://mailtrack.io/trace/link/93b404ea1eafd1c7f496d02fe5ce46e67a531351?url=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1nK1mq1r8t6Q7W9VnszgIQi4alVvx5aIY%2Fview%3Fusp%3Ddrive_web&userId=82877&signature=9c0b7d9890c4c9ab>
​attach is the psd. In order to view the background color on Avocode I have
to double click the right and inside there's a psb file with the
"problematic" background color.

Thank in advanced.
Or.


‌
<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by jakubzitny** [comment]
Thanks for the info @orhar. We have already fixed this in our internal releases, please give us few weeks and we'll let you know when it's out.

You can also join our [Avocode Community on Slack](https://community.avocode.com) to have a beta version earlier.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. It was caused by color profiles, which should be ignored with the new rendering engine.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
