### ISSUE TITLE
Processing failed

### ISSUE THREAD

**Issue by berdusan** [avocode/avocode#1739]
Sketch 
* **Version**: Avocode 2.16.4

* **Web/Desktop**: Both

* **Platform/Browser**: Chrome
MacOs Sierra

Ivan.berdusan@c14torce.com

* **project**: Hero model
Processing failed on update

**Comment by bolekkerous** [comment]
Hey -
it looks like you're using Avocode 2.16.4, which is an outdated version.

Could you try to update your Avocode and then reupload the design? It would help us figuring out whether the problem is still relevant in the current version.

You can check from update from in-app system menu or you can download the installer here:

https://avocode.com/download

**Comment by berdusan** [comment]
i will update files by tomorrow, and let you know. thanks for the quick answer
