### ISSUE TITLE
Question about rendering/downloading of designs

### ISSUE THREAD

**Issue by crh225** [avocode/avocode#1823]
* **Version**: 
latest

* **Web/Desktop**:
not the electron version

We have gone through a few contract designers. All use sketch and export to avocode. 
The original designers files, when opened in the inspect mode in avocode downloaded two files to render the entire complex design.

New designer now, and when they upload to avocde, it has to download 500 layers just to render the image. Is this a setting in sketch or avocode to make it not download each layer separately?

**Comment by crh225** [comment]
The original designer files that downloaded where preview.png that was the entire design. small.png and sprintes.png

small.png
![image](https://user-images.githubusercontent.com/19475195/35173226-4d2cec96-fd30-11e7-8928-4d5b80db727a.png)

sprites.png
![image](https://user-images.githubusercontent.com/19475195/35173237-55792aae-fd30-11e7-80af-69e01ac7f1b2.png)

and then it downloads the entire design which looks like this
![image](https://user-images.githubusercontent.com/19475195/35173255-649d1266-fd30-11e7-8e42-7ac4e85abe9d.png)

**Comment by crh225** [comment]
Could this be because the other designer could somehow flatten the files somehow into one new layer, and keeping everything inspect-able in avocode?

**Comment by jakubzitny** [comment]
Hi @crh225, the difference between the number of assets that are being downloaded were actually changed by Avocode, it's not because of the designer. We download all layers all the time so the designs are better prepared and more flexible for devs. We keep improving the performance of downloading assets, so it should be faster now than before.

Did I understand it correctly that this was the main problem for you? The number of layers and speed of initial design download in Avocode?

**Comment by crh225** [comment]
Speed is still a major problem. Closing as you cant help me without me emailing you my sketch file.
