### ISSUE TITLE
em pt vw and so on

### ISSUE THREAD

**Issue by OdedYaron** [avocode/avocode#1836]
Hi Avocode team,
I love it if you can add support to all this measurement on your next update for the web developer.

Regards,

**Comment by vojtatranta** [comment]
@OdedYaron PT,  are included in the app already. EMs are not available intentionally because they are relative to font size which is inherited from every parent element in the HTML cascade. That's the reason why we only went with REMs units, because they are relative to to root HTML element.

To se REM units go to App preferences - Code tab - select Advanced options while select your template language (CSS, LESS, SASS etc.)

To use pt units (which are mostly used in the mobile development) got to settings of every design. This button is located in the cog on every design tile in project manager. Or it is located in the bottom right of opened design.

VWs we may include in the future for sure.

**Comment by OdedYaron** [comment]
Thank you very much.

Regards,
Oded
