### ISSUE TITLE
Zoom / scaling quality is terrible

### ISSUE THREAD

**Issue by BrandonLive** [avocode/avocode#184]
Even at 100% zoom in the app (which is often really small), it renders blurry text and generally looks very poor in comparison to the same file in Sketch on my designer's machine. This gets even worse if I zoom the document. In Sketch it nicely re-renders at the new zoom level. Avocode just seems to do a bitmap scale of the rendered content. While this doesn't block the functionality I need to do my work, it makes for a crummy experience and makes Avocode look amateurish.

Some of this (at least at 100%) may be an issue with Avocode on high DPI displays (I don't have a low-DPI display in my office to test it on to see if it's any better).

**Comment by marekhrabe** [comment]
Avocode is supposed to use bitmap scaling on documents. We, in fact work with just bitmaps of layers from Sketch. Otherwise we would need to be able to render perfectly every feature that Sketch supports and that is quite hard task to do and also you would need all used fonts installed on computer when inspecting. Not saying we won't arrive to that stage someday, but nowadays we just show bitmaps for reasons listed above.
