### ISSUE TITLE
Text disappeared in XD designs

### ISSUE THREAD

**Issue by dimastrapchev** [avocode/avocode#1962]
With the new update, text disappears in XD designs.

![screen shot 2018-04-04 at 3 51 32 pm](https://user-images.githubusercontent.com/15209814/38311945-b1ac8eee-3820-11e8-865a-612dbb5245e3.png)
![screen shot 2018-04-04 at 3 51 49 pm](https://user-images.githubusercontent.com/15209814/38311946-b1cbab76-3820-11e8-968d-83e37b433077.png)

---
* **Version**: 2.22.0
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 274952
---
```
No stack trace available
```

**Comment by bolekkerous** [comment]
Hey, @dimastrapchev -
we know about this issue and I believe it is already fixed internally. The fixed version should be released publicly next week.

In the meantime, the workaround is bring any text layers to the front and remove them from any groups and resync again. Otherwise we could also send you the previous version, which should work correctly.

**Comment by dimastrapchev** [comment]
Hi Bolek,
we have already many designs in the avocode and it would be great if you could send the previous version for Linux 64 to my colleague (arsovska@fitanalytics.com <mailto:arsovska@fitanalytics.com>) while we are waiting for the fixed version.
Thanks!!
Dima

**Comment by bolekkerous** [comment]
Hey, Dima - 
actually we decided that we should be releasing a quick fixed version tomorrow. Should we still send the previous version to the email?

**Comment by dimastrapchev** [comment]
Great! No need for the older version then. Thanks!

**Comment by vojtatranta** [comment]
We are releasing a fix today.

**Comment by petrbrzek** [comment]
Fixed in 2.22.1.
