### ISSUE TITLE
Sketch symbol broken

### ISSUE THREAD

**Issue by mahish** [avocode/avocode#1983]
* **Version**:  2.23.0

* **Sketch plugin version**: 49.3.0 and 49.0.0

* **Web/Desktop**: both

* **Platform/Browser**: MacOS 10.13.4, Firefox 59.0.2, Chrome 65.0.3325.181

**Avocode e-mail**: jiri.maha@avast.com

When we open Sketch artboard in the Avocode the symbol looks right. When we open the symbol, the symbol gets broken. See attached screenshots (both app and web version of Avocode). It has been happening with more symbols, on all computers & users.

Sketch artboard (app)
![app-artboard](https://user-images.githubusercontent.com/3687943/38920831-869cfe76-42f4-11e8-962b-b85b99ed1a61.png)

Sketch symbol (app)
![app-symbol](https://user-images.githubusercontent.com/3687943/38920832-86ba6362-42f4-11e8-9f52-e6c76e1829f0.png)

Sketch symbol (web)
![firefox-symbol](https://user-images.githubusercontent.com/3687943/38920833-86d3cc44-42f4-11e8-96e0-4001badc5506.png)

**Comment by bolekkerous** [comment]
Hey - 
this is an issue with symbol overrides, which we're not yet supporting 100% correctly.

However we will release a new version this week with the ability to import Sketch files directly into Avocode via drag n drop. The symbol issue will be fixed for the files that will be imported directly into Avocode, for Sketch files uploaded through plugin, the issue should be fixed a while after that.

**Comment by mahish** [comment]
@bolekkerous Thanks for info. Can you confirm this release will fix also the color code issue as mentioned here: https://github.com/avocode/avocode/issues/1714#issuecomment-343904852 ?

**Comment by jakubzitny** [comment]
Hi @mahish, we've just released a new version of Avocode. Two things here:

1. The symbols/overrides support are as follows: If you upload your Sketch file by dragging and dropping it to Avocode (not via Sketch plugin) you'll be able to inspect overriden symbols directly in the artboards they are contained in. If you click on the symbol however, and open the original master in new tab, you'll only get the master without overrides.


2. Regarding the weird colors. I believe we've partially fixed the problem a few versions back. The problem only persisted in Sketch files saved in Sketch v47 due to a weird format they used. This should be fixed when you re-save the file in newer version of Sketch. However, if you still see that happening after you re-save it, please let us know by creating a new issue here.


Thanks 😉
