### ISSUE TITLE
Just got spammed by 40 notification e-mails

### ISSUE THREAD

**Issue by BrandonLive** [avocode/avocode#209]
My designer just synced up updated designs for our project (which has about 40 "artboards" now in 2.0). I then got 40 e-mails, one for each page of the project. I don't think she actually changed all 40 (which is another issue), but that's sort of beside the point.

I do think notifications for updates are handy, but you should group them into one e-mail. This should be especially easy when she's syncing one project from Sketch as one operation, but even if that weren't the case, I think you should be batching notifications (i.e. hold off sending the mail until a minute has passed since the last notification trigger).

I'd also expect the same batching behavior if/when you have Slack integration.

**Comment by rychlis** [comment]
Sorry about that, we've just introduced email notifications yesterday and this behavior is not flashed out yet as it should be.

We will definitely send just one notification for a sketch design sync, right now there is a notification for each page which leads to the spamming because the sketch extension updates all the pages every time a designer creates a new revision or document.

**Comment by rychlis** [comment]
You will now get notified about sketch sync only with one notification - this applies to email, web notifications and slack as well.
