### ISSUE TITLE
Exporting is limited in lite version: What does it mean?

### ISSUE THREAD

**Issue by TiloNN** [avocode/avocode#2108]
When I try to export images, then the export button is inactive and a tooltip tells me: 
Exporting is limited in lite version.

![2018-08-02 11_10_46-greenshot](https://user-images.githubusercontent.com/12526638/43574602-ef19e042-9644-11e8-9104-c80b315a3cb2.png)

What does it mean?
Google has no answer.
Complete new installation did not help.

I tried the web app -> it works.
I tried my credentials on a different machine -> it works.
I tried other credentials on my machine -> it works (as far as I can see, because of the different designs; xd instead of sketch).

Any ideas what happens here?
Thanks for helping.

I'm using the latest version.

---
* **Version**: 3.3.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 24209
---
```
No stack trace available
```

**Comment by jankuca** [comment]
Hello,

you most likely have the **Monroe rendering engine** turned off in app settings. Monroe engine is our state of the art rendering engine which draws designs. **When Monroe is disabled, we are unable to render individual layers for Adobe Xd files** which is why exporting is disabled. We call this limited mode the "Lite" mode.

Layers from Photoshop and Sketch files can still be exported with possible lower precision when Monroe is disabled as our legacy rendering engine supports these formats. Xd, however, is only fully inspectable with Monroe enabled.

If you do not have the Monroe engine disabled in app settings, this might be happening due to **WebGL not being available** (because of your graphics card) or **the rendering process being too resource heavy** (at which case an error message should pop up) causing the app to switch to the "Lite" mode to allow limited inspection rather than none.

**Comment by TiloNN** [comment]
I did not deactivate the Monroe rendering engine.
![2018-08-02 11_52_43-greenshot](https://user-images.githubusercontent.com/12526638/43576980-e2b699de-964a-11e8-93bd-dc495fdd105a.png)

I'm not working with Xd files, but try to export images from sketch designs.

I'm using a system with two graphic cards inside and now I assigned the 3D card to avocode.
![2018-08-02 11_55_19-greenshot](https://user-images.githubusercontent.com/12526638/43577163-68ba9832-964b-11e8-835b-b187825f21f8.png)


![2018-08-02 12_00_15-greenshot](https://user-images.githubusercontent.com/12526638/43577271-aeaa48e2-964b-11e8-8605-c5348d5d1b16.png)

No changes.
At least my browser supports webGL and my browser does not use the 3d card.
![2018-08-02 12_04_13-greenshot](https://user-images.githubusercontent.com/12526638/43577493-44361698-964c-11e8-9c92-14f030211ee5.png)

Any idea how to convince avocode to use not the lite mode?
Would be great.

**Comment by jankuca** [comment]
Is there any message popping up when you open the design?

To me, it sounds as if the app is unable to render the design due to resource limitation. How much RAM do you have?

**Comment by TiloNN** [comment]
No popping message.
Is there a kind of log I can take a look inside?

It is an old dual core with 8GB RAM:
![2018-08-02 12_48_02-greenshot](https://user-images.githubusercontent.com/12526638/43579447-6693c8ce-9652-11e8-882e-9d3c18f7d28b.png)

**Comment by jakubzitny** [comment]
Thanks for the info @TiloNN, we investigated these problems and it seems that the problem is specific to your design(s). It's probably a bug on our side and it should work for you properly. We're searching for the root cause of the problems and we'll get back to you asap.

**Comment by jankuca** [comment]
Ok, we think that your issue is caused by your GPU being blacklisted for WebGL use. The blacklist will eventually be updated when Avocode starts using a newer version of [Electron](https://electronjs.org).

You can try disabling this blacklist manually by starting the app with the `--ignore-gpu-blacklist` option. It is, however, possible that the app will not work correctly with this disabled – you might encounter parts of the app being rendered black.

The option can be set by modifying the properties of the shortcut you use to start Avocode:
- Right click on the shortcut, and select Properties
- At the very end of the *"Target"* text box, add a space and then `-- --ignore-gpu-blacklist`.
It should end in something like `...\Avocode.exe" -- --ignore-gpu-blacklist`

**Comment by TiloNN** [comment]
Indeed. 
Seems to be the problem.
Unfortunately it is not helping me much.
I can export, but the result is awful.

![2018-08-02 16_30_09-greenshot](https://user-images.githubusercontent.com/12526638/43590650-cb1ba43c-9671-11e8-8bb2-bcd972cee4a4.png)
![3-layers](https://user-images.githubusercontent.com/12526638/43590712-eefb3bb0-9671-11e8-85cf-7b2794beb245.png)

I .. have to work on a other machine and hope, that it will work some day again.
Thank you for your support.

**Comment by jankuca** [comment]
I'm glad that we at least tracked down what the issue was. We will try our best to update the internals so that this does not happen.

You can optionally try disabling the Monroe engine for now. Since your designs are from Sketch, they are inspectable even with the engine being turned off. There might be minor differences in rendering (effects, blending modes, complex shapes, …) and some layers might not have good exports but by looking at the screenshot you posted, I think you might be fine even with the legacy renderer.

**Comment by TiloNN** [comment]
That was a good idea.
I disabled the Monroe engine and the results are much better.
But not as good as with a working Monroe engine, right?
So .. it is still better to use a device that support this engine.

**Comment by jankuca** [comment]
Yes, like I said, there are minor differences in the rendering. Monroe renders designs very precisely and supports advanced features in designs whereas the legacy exporter has problems with clipping masks combined with blending modes or strokes, some shapes get rendered slightly incorrectly and measures might not be as good.
