### ISSUE TITLE
Pixel checker is not transparent on Linux

### ISSUE THREAD

**Issue by lubomirblazekcz** [avocode/avocode#2318]
* **Version**: 4.11.0
* **Web/Desktop**: Desktop
* **Platform/Browser**: Ubuntu 20.10

When using pixel checker on Ubuntu, the background is not transparent, so the pixel checker cannot be used. This might happen on other distros too, didn't test it though. It was working before, maybe it broke in some update? But it's a while since it's not working, so I cannot tell when.

**Comment by jakubzitny** [comment]
Hi @evromalarkey, this has been fixed in the latest version of Avocode. Please update, and if it still doesn't work for you, please follow the instructions in [our Help Center](https://help.avocode.com/en/articles/1673402-align-your-website-or-mobile-app-with-the-pixel-checker-tool-in-avocode#troubleshooting).
