### ISSUE TITLE
Error when opening design for the first time

### ISSUE THREAD

**Issue by tayemaker** [avocode/avocode#251]
I've been getting an intermittent problem when opening a design for the first time in the app. I'd say it happens about 33% of time. After I click cancel and then open it again it works.

**Comment by petrbrzek** [comment]
What exactly is the problem? We need more information to debug it.

**Comment by tayemaker** [comment]
![avocode](https://cloud.githubusercontent.com/assets/12429766/7654003/c0beb96a-fb11-11e4-9163-532e7b5d1232.png)

I get this screen when opening a design for the first time. It work the second time I try to open it.

**Comment by mexdevs** [comment]
We get the same error on some designs but are not able to open them no matter how many times we try. The same design can be opened by some but not other team members so it seams to be related to corrupt data in the app, not the design.

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.

@mexdevs your issue is probably a different one as you experienced loading fails persistently. We've also addressed this problem in Avocode 2.2.0 which handles the problem much better and let's you know about corrupted designs.
