### ISSUE TITLE
Keystroke events fires when typing into the export textbox

### ISSUE THREAD

**Issue by monti84** [avocode/avocode#319]
https://youtu.be/VjnTr9evmYw
I have discovered this really annoying bug weeks ago, still not fixed.
I'am using the app on windows 7.

**Comment by rychlis** [comment]
This was fixed in 2.2.0 but you are using an older version, please download the latest version of Avocode here - https://manager.avocode.com/downloads/

We're going to notify all people with older versions of Avocode soon, the latest version 2.2.1 has also in-app update notification which will help.
