### ISSUE TITLE
Cannot Import Sketch files without Sketch Extension

### ISSUE THREAD

**Issue by benceg** [avocode/avocode#361]
When I attempt to upload a `.sketch` file from Dropbox from within the Avocode Manager, I am not able to do so. The only allowed file formats based on the query string of the Dropbox upload window are `jpg`, `jpeg`, `png` and `psd`.

**Comment by marekhrabe** [comment]
This is a limitation of our current technology. You need to sync Sketch files using a Sketch Plugin. If you don't own Sketch, ask your designer if he can sync the design for you.

We are working on a better solution that can work completely without Sketch app, but it may take us some time to develop this as Sketch file format is still relatively new, not much documented and tightly coupled with native Mac Frameworks and runtimes and it is kind of hard to make all this work reliably and cross-platform.

We will keep this thread posted. Until the solution is out, try to have your files synced by someone with Plugin or in case of need, pass the Sketch file to our support and we can sync that for you manually.

This issue is also tracked in our Uservoice where you can vote to prioritize the task: https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7041131-allow-uploading-sketch-files-in-the-project-manage

**Comment by benceg** [comment]
Thanks for your quick response @marekhrabe!

So just to double check - is Dropbox upload support for `.sketch` files on your radar? Or is the work you're doing only toward using the Manager interface to manually upload `.sketch` files?

**Comment by marekhrabe** [comment]
We treat upload from computer and Dropbox exactly the same, so when it is ready, it will work for both cases.

**Comment by benceg** [comment]
That's wonderful to hear! Thanks Marek.

On Fri, Jul 24, 2015, 10:43 Marek Hrabe <notifications@github.com> wrote:

> We treat upload from computer and Dropbox exactly the same, so when it is
> ready, it will work for both cases.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/avocode/avocode/issues/361#issuecomment-124444815>.
>
-- 
Ben Ceglowski
Phuse.developer()

**Comment by chielsen** [comment]
This seems to me as a must have feature. Main use for avocode is to read sketch files on Windows.

**Comment by ellioseven** [comment]
+1 Not being able open sketch files directly is a massive deal breaker.

**Comment by mochabcha** [comment]
Well there have been improvements on the plugin and Sketch thankfully.  Its a little more reliable.  But despite a recent UI upgrade, its still quite useless without the plugin.  Even just an error message or the pointing out the layer that’s causing the problem would be nice.  Making things in Sketch only to find that you have to manually export them slice by slice to your developers (who use Linux) is pretty frustrating.  

The fact that Sketch has such a labor intensive exporting feature is also quite frustrating.

**Comment by vojtatranta** [comment]
You can add your votes to the wish at uservoice: https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7041131-allow-uploading-sketch-files-in-the-project-manage

As you can see, we are planning such feature as soon as possible.

**Comment by meiraleal** [comment]
Nothing yet? :(

**Comment by jakubzitny** [comment]
@meiraleal Unfortunately not.

There were more urgent changes on our todo list and we will be releasing new version of Avocode with them shortly. Parsing Sketch files directly is (again) one of the top priorities for coming months.

Stay in touch ;)

**Comment by Roobyx** [comment]
Should have read this thread before starting the trial. Started it because of this feature only... :/

**Comment by jakubzitny** [comment]
@Roobyx We're expecting to have this implemented in fall. For now you can use our Sketch plugin for syncing between Avocode and Sketch.

**Comment by blcarson** [comment]
Any updates on this?

**Comment by rickmurt** [comment]
Any updates?  We're past fall :)

**Comment by chielsen** [comment]
Yes thinking of cancelling subscription as I'm waiting for 15 months already.

**Comment by vojtatranta** [comment]
@chielsen @rickmurt
Sorry guys, it's very complicated thing. The extension is now simply required, because sketch format is not easily parseable.

We already have an internal version of parser available and we started working on direct upload of sketch files. 

We are now busy with Avocode on the web which requires all of our resources. 

And current estimate fr sketch direct upload is June (Q2).

We completely understand your struggles. So if you ping us at team@avocode.com mentioning this issue and your accounts on Avocode we will arrange some discounts for you if you wish.

**Comment by akifuygun** [comment]
2 years :/ **2**

**Comment by jakubzitny** [comment]
Hi everyone, we've just released Avocode 2.24.0 with support for dragging and dropping Sketch files directly from macOS, Windows and Linux. Please update, give it a try and let us know if you have and issues with it 😉
