### ISSUE TITLE
Newest revisions not syncing

### ISSUE THREAD

**Issue by stofi** [avocode/avocode#428]
Avocode app is not downloading the newest psd revisions of my designs. My project folder states it was "last active about an hour ago" but the designs inside are days old.
I can see the latest revisions on the web.
Is there a way to force download them from the cloud?

**Comment by rychlis** [comment]
That might have happened because the revision took a long time to process or failed to process.

We show the new revisions on web right after you upload the psd but it's still processign for some times before you can see it in app. Please give us an email at team@avocode.com so we can check your designs and see what happened.

Thanks and sorry for the delayed answer
