### ISSUE TITLE
Export to Avocode error (Sketch 3.4 beta)

### ISSUE THREAD

**Issue by 2gen** [avocode/avocode#437]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/datpham/Library/Containers/com.bohemiancoding.sketch3.beta/Data/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by rychlis** [comment]
Hi sorry we don't support Sketch 3.4 beta yet as there were some big changes, we're working on it though

**Comment by pierrelucgagnon** [comment]
Hi, i'm having the same issue but with Sketch 3.3.3

Sketch Exporter 2.1.1 running in Sketch 3.3.3

TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/plgagnon/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)

**Comment by pierrelucgagnon** [comment]
We've been doing test for 2 hours now; I tried to remove all images, different elements within artboard to see if it's a specific thing making this problem but I can't find. I must say that It's kind of annoying that we just paid for a subscription to avocode and then it's interrupting the flow of our development process. Hope you guys can find a solution! Otherwise this software is really amazing.

**Comment by marekhrabe** [comment]
We are working on a new major release of Sketch extension for some time. It fixes a lot of bugs including this one. We will notice you when the new version is released. I will leave just one issue about this topic open: #472
