### ISSUE TITLE
Desktop Syncing Errors

### ISSUE THREAD

**Issue by BenTremper** [avocode/avocode#503]
Can't get any of my projects to sync. I can export the web fine, but desktop syncing is not happening even after deleting / reinstalling. 

![screenshot 2015-10-27 17 04 10](https://cloud.githubusercontent.com/assets/11984087/10775297/c3a1fdee-7ccc-11e5-933e-ea68fb1fb480.png)

**Comment by rychlis** [comment]
Hi, what version of sketch and sketch extension are you using? It looks like you used the 2.1.2 extension which might cause this error, you will need to re-sync the design with 2.1.3 https://manager.avocode.com/downloads/#plugins

**Comment by JorindeReijnierse** [comment]
I had the same problem and it appears it was caused by the sketch update + sketch plugin update.If a project already was synced with the older version of sketch and then synced again with the new sketch update + plugin-update, the syncing didn't work anymore (it either showed 'processing failed' or just 'downloading' for ages) .I fixed it by deleting the project, made a new project and then synced the project again using the updated sketch plugin and that works.

**Comment by BenTremper** [comment]
Yep, I had to do the same. Needed to delete all prior projects and resync
after the new update.
Thanks!
Ben

*Ben Tremper Design*
Interaction Design / Visual design

1301 Yellow Pine Ave, Unit B
Boulder, CO 80304
www.bentremper.com

O: (720) 583-2503
M: (720) 346-3882

**Comment by launchsequence** [comment]
My sketch project was synching fine during free avocode trial, purchased license and updated both app (2.4.3) and plug in (tested 2.1.1 / 2.1.2 /2.1.3) and it crashes everytime on metadata stage of sync. Tried synching as update and new project. 

It will synch other "new" projects, but not the one I am currently working on even if I revert to past versions of the file that DID synch. On a deadline on a large global project and I need an urgent fix. Thanks.

**Comment by rychlis** [comment]
@launchsequence the crashing in metadata stage is a different issue - #497

We've just fixed it with release of sketch extension 2.1.4 https://manager.avocode.com/downloads/#plugins

**Comment by launchsequence** [comment]
@rychlis Just updated. Seems to have solved the issue. Thanks. Will post further happenings.
