### ISSUE TITLE
No option to delete artboard

### ISSUE THREAD

**Issue by conniechau** [avocode/avocode#506]
![screen shot 2015-10-30 at 2 00 19 pm](https://cloud.githubusercontent.com/assets/11649605/10853827/9c24d43c-7f0e-11e5-892c-222287a014e1.png)

**Comment by jankuca** [comment]
Hello, yes this is intentional. We do not support structural "design group" (Sketch group) modification. There will be a change in the way the Sketch extension uploads artboards soon. These will become standalone designs which will be deletable. We'll notify you about further updates about this issue.

**Comment by conniechau** [comment]
Hi, thanks for the reply. So in the future, will I be able to pick exactly which artboards/pages I can upload to Avocode?

**Comment by jankuca** [comment]
Yes, definitely. This feature is currently being implemented. Stay tuned.
