### ISSUE TITLE
One PSD updates as second

### ISSUE THREAD

**Issue by isikora** [avocode/avocode#595]
It happens with several files. For example I upload two psd files - 1.psd and 2.psd. After that I hange 1.pds und update with Photoshop plugin. I open Avocode Manager and see only one file, open preview fith browser and inside 1.psd I see 2.psd. I observed that it happens when I have both files opened in Photoshop.

**Comment by jakubzitny** [comment]
Hi, thanks for the report. We'll look into this and come back to you with an update.

**Comment by jakubzitny** [comment]
Hello again, we've tried reproducing this issue but we were unable to do it. Everything worked for us, but maybe a hidden unhandled issue with Photoshop could cause that. Can you please send us more details about your system, Photoshop version and our Photoshop extension version?

In the meantime you can "reset" the sync between Avocode Manager and Photoshop yourself. Just use `Sync as a new Design` for both of the designs and let us know if it worked.

Thank you.

**Comment by isikora** [comment]
Hello, I have all the time this issue. Problem is even bigger because developers cannot download files this kind of files. I am sending a screen. On the left side we can see file named design-340[...] opened in Photoshop. On the right side we see file called design-324[...]. opened in Avocode. What happend?

1. Earlier I synchronized by Avocode plugin in Photoshop file called design-324[...]
2. Today I synchronized by Avocode plugin in Photoshop file called design-340[...]
3. Avocode plugin even didn't ask me to choose destination folder project in Avocode, It synchronized immediately this file.
4. I opened Avocode projects by browser I I saw that I cannot even see file named design-340[...], but I can see that preview od design-324[...] looks like design-340[...].

Please do something with it because we cannot work!

![screen shot 2016-02-18 at 11 22 42](https://cloud.githubusercontent.com/assets/16683077/13140465/9a32c988-d632-11e5-8e29-fe9bebc9f862.png)

**Comment by jakubzitny** [comment]
Hi, so case might be: If you originally created the second design (design-340) from the first one (design-324) by `Save as` in Photoshop, it might have copied the reference to Avocode as well. And that's why it is still replacing the old design.

However, there is an option in the Avocode plugin in Photoshop to `Sync as New Design`. If you Sync the newer design (design-340) as "new design" it should create separate design in Avocode. Have you tried this option please?

![9a32c988-d632-11e5-8e29-fe9bebc9f862](https://cloud.githubusercontent.com/assets/3315662/13141940/3600564e-d63a-11e5-8b97-73a878174fae.png)

**Comment by isikora** [comment]
Yes I tried but it is not user friendly, this is not the solution because instead one click I have to:
1. Upload all the time as a new design after file update plugin still overwrites old file
2. Delete old files, 
3. Call it with different name and write do developers that they have to make changes because they use old one.
This is a huge problem when processing our work and must be fixed. Avocode is useless for us now, finally we have to upload files for developers with InVision.

**Comment by jakubzitny** [comment]
Not really. Once you Sync it as a New Design, it holds new "reference" so all synchronization is done with this new design. Just try it on both designs you had problem with (or more if you have problem with more of them) and let me know if it still rewrites the old one. It should not.

And in the future just use the `Sync as a New Design` everytime you create a "new design" using Save As. That's why it is there. I agree the scenario you just described is painful and totally user unfriendly, however, it is not supposed to work like that and we are not even able to reproduce it.

Please let me know what versions of Photoshop and Photoshop plugin you are using.

Thank you.

**Comment by bolekkerous** [comment]
To avoid this problem in the future, you can just use the upload by drag and dropping the file to Avocode, which always creates a new file unless you drag and drop it over an existing design, which will create a revision.

I'll close this issue due to inactivity - if you still experience this or any other problem, please create a new issue or comment here.

Thanks.
