### ISSUE TITLE
Syncing with Sketch doesn't work

### ISSUE THREAD

**Issue by rewardexpert** [avocode/avocode#779]
1. Multiple artboards doesn't work. It loads my laptop so fan is spinning like crazy. But after 10 min wait. I have  processing failed. 

2. When I upload as separate artboards, it worked for some, but for some - same thing. 
Screenshot: http://joxi.ru/QY2LzRBiqlaer6.png

This is ongoing problem. I used to have a stable way to sync artboards using some trick when I open up link in browser. No I don't have any new way to do it. Help.

**Comment by jakubzitny** [comment]
Hi, thank for the report, we're sorry to hear that. Can you please give us more info on the versions of Avocode, Avocode Sketch plugin and Sketch you are using?

Thank you.

**Comment by bolekkerous** [comment]
We've checked the sketch file and found the problem. Unfortunately, we probably won't be able to fix it on our side right now.

The problematic artboards are the ones with huge amount of layers. Those artboards have so many layers that Sketch can't handle the RAM load when it tries to feed all the layers info to our plugin.

Because of that, I would advise you to slice those artboards to few smaller ones (header, 1st section,...). Another thing that could help would be to rasterize some illustrations into a bitmap, if it makes sense for the case.

We're sorry for the inconvenience.
