### ISSUE TITLE
Sync is failing to upload any design file

### ISSUE THREAD

**Issue by Eranayalon** [avocode/avocode#827]
Avocode sync: 3.3
Sketch 3.7 (Latest)

I'm afraid it' because I've updated sketch version..

I can't upload designs since i updated sketch. the same design file has synced before the update.
Why don't you allow upload from web?? i'm now stuck and can't send designs to dev team

**Comment by akifuygun** [comment]
same problem here

**Comment by connor-bean** [comment]
Hello, 

Thanks for reaching out. Could you send us the log files and the problematic design to team@avocode.com?

Here is a guide on how to get log files - https://github.com/avocode/avocode/blob/master/sketch-plugin.md#reporting-bugs

Thanks,
Connor, Avocode Team

**Comment by akifuygun** [comment]
Just sent the file.

**Comment by Eranayalon** [comment]
Me too, thanks

**Comment by connor-bean** [comment]
Thank you! I see both log files in my inbox. I'm going to pass this along to my dev team.

Please let me know of any other questions.

Connor, Avocode Team

**Comment by connor-bean** [comment]
Can you send us the sketch file as well to team@avocode.com?

Thanks,
Connor

**Comment by Eranayalon** [comment]
I've sent mine again

**Comment by akifuygun** [comment]
Me too.

**Comment by rychlis** [comment]
It seems that the issue is caused by text layers with the `.SF NS Display` and `.SF  NS Text` Typeface (might affect other typefaces starting with dot).

These layers seem to be stored differently that usual which is not handled properly by our plugin. If you change the Typeface of such layers to different one and then immediately set the typeface back to `.SF  NS Text` the layer will export without problem.  We'll do more research and try to fix this ASAP

**Comment by k2batuhan** [comment]
thank you for your supports guys, we are solve the problem :+1:

**Comment by Eranayalon** [comment]
OK, it's success thank you :)
anyway this didn't happened before the update with the same file...

**Comment by rychlis** [comment]
Hi we have released Sketch Plugin 3.4.0 that should fix this completely. Update [here](https://github.com/avocode/avocode/blob/master/sketch-plugin.md#installation--update)

Thanks for your cooperation!
