### ISSUE TITLE
SOCKS5 proxy connection

### ISSUE THREAD

**Issue by szymonmichalik** [avocode/avocode#830]
Mac app doesn't work when connected with SOCKS5 proxy.

**Comment by connor-bean** [comment]
Hey, thanks for the ticket!

Since you're using a proxy, here is a guide to properly set it up in Avocode:

https://avocode.zendesk.com/hc/en-us/articles/203402352-How-to-use-a-proxy-server

Also, this another article may help - those are domains we are using and which may be needed to be whitelisted on your side if you are under restrictive proxy or firewall:

https://avocode.zendesk.com/hc/en-us/articles/205022361-Used-domains-to-whitelist

Please let me know if this does not solve your problem.

Thanks,
Connor, Avocode Team

**Comment by szymonmichalik** [comment]
Hey,

The guide you have mentioned refers to HTTP/HTTPS proxy and I had submitted a bug with SOCKS5 proxy configured with Network preference pane.

The case is to either enable SOCKS5 proxy settings within Avocode, or to detect system network settings .

Thanks,
Szymon
