### ISSUE TITLE
Exporting symbols from sketch

### ISSUE THREAD

**Issue by Fabionunez** [avocode/avocode#842]
When I export the symbols from sketch to avocode, the symbols apear, but the layers have wrong "width" position. All the layers have negative witdh.

**Comment by Fabionunez** [comment]
I'm seen now that the problem it doesn't happen when the symbol is in the position x:0 y:0, but when you have other symbols in other coordinates, all the layers inside them are wrong.

any way to solve it?

**Comment by slacku** [comment]
There is a problem with measuring elements from Symbol's page too. When I put the same layers to another artboard, which is not Symbol, then measuring in Avocode works perfectly.

**Comment by connor-bean** [comment]
We know that we currently do not support the new Sketch Symbols functionality very well.

We're going to investigate the possible solutions of this problem later this week.

You can track the progress on the github issue #845 
https://github.com/avocode/avocode/issues/845

Please let us know of any other questions.

Thanks,
Connor, Avocode Support

**Comment by bolekkerous** [comment]
Symbols are now treated as sub-documents (same as smart objects), so in order to inspect them, you need to double click them on them in the design.

Measuring from symbols in the design should also work properly (but you need to open it to inspect the elements inside of it).

We will probably rework this behaviour of symbols in the future.

If you have any suggestions or problems with the symbols at the moment, please comment here or create a new issue.
