### ISSUE TITLE
Problem with uploading Sketch File

### ISSUE THREAD

**Issue by ljanecek** [avocode/avocode#859]
Plugin is not able to upload the artboard, process of sync ardboars freezes (more than 60min) and there is no any alternative to upload it.

![image](https://cloud.githubusercontent.com/assets/2696545/15115112/a838f042-15fd-11e6-9f75-2c3b4d01b8ea.png)

![image](https://cloud.githubusercontent.com/assets/2696545/15115143/df13a724-15fd-11e6-8ccf-467ab31e68d2.png)

**Mac mini (Late 2014)**
Version: 10.11.4 (15E65)

**Sketch**
Version: 3.7.2 (28276)

**Avocode Plugin** 3.5.0

**Comment by connor-bean** [comment]
Hey, thanks for the report.

Could you send us the log files from Sketch? Here is a guide on how to get log files - https://github.com/avocode/avocode/blob/master/sketch-plugin.md#reporting-bugs

Another thing that would really help us is if you could upload the problematic design for us so we can see what exactly causes the problem.

Could you send us the design and the log files to team@avocode.com instead of posting them here?

Thank you,
Connor, Avocode Team

**Comment by ljanecek** [comment]
**This is the last activity:**

AvocodePlugin: normal scale
AvocodePlugin: layer 1 (DA44EFC5-48A6-40C2-9ACD-239FB7B729D2)
AvocodePlugin: normal scale
AvocodePlugin: layer 2 (60053725-C15D-476C-A036-B09A477DFBD8)
AvocodePlugin: normal scale
AvocodePlugin: layer 3 (31D06E32-85E8-48FC-A34D-729812BD765B)
AvocodePlugin: normal scale
AvocodePlugin: layer 71 (FE2E6FD8-4B9A-4C1A-8B1B-552D0F5D0668)
AvocodePlugin: layer 0 (986C7702-A833-4387-AB20-327198BD5545)
AvocodePlugin: normal scale
AvocodePlugin: layer 1 (C3AA074E-1795-422F-A770-EE1B9869FE7C)
AvocodePlugin: normal scale
AvocodePlugin: layer 2 (B540C026-765D-4930-8542-DAA04126BEFC)
AvocodePlugin: normal scale
AvocodePlugin: layer 3 (DCFCFC08-59AB-4D71-B54D-CD6F8F313322)
AvocodePlugin: normal scale
AvocodePlugin: layer 4 (14B64C65-4FAD-47C2-A7FF-BD57F2E53908)
AvocodePlugin: layer 0 (D66EBAB0-A31F-4A16-89E9-CC8AF9DD9FA8)
AvocodePlugin: normal scale
AvocodePlugin: layer 1 (CF4DE0A0-9963-4220-97DF-A84C4F2BEABA)
AvocodePlugin: normal scale
AvocodePlugin: layer 5 (13315C50-FDF3-46BB-A4CB-A03EA766389E)
AvocodePlugin: normal scale
AvocodePlugin: layer 6 (E7255B4B-E197-448F-B266-E8151C47EEC8)
AvocodePlugin: normal scale
AvocodePlugin: layer 72 (3480F93D-BABE-46E1-98A2-E2C560EA61CE)
AvocodePlugin: normal scale
AvocodePlugin: layer 73 (E2FC03FC-09B0-42DF-987C-AE94C5E489B7)
AvocodePlugin: normal scale
AvocodePlugin: layer 74 (09C8A852-3898-469D-9BC4-C095D07013E3)
AvocodePlugin: normal scale
AvocodePlugin: layer 75 (0FE7929A-69B1-4CC6-ACD5-FFA5801E71B4)
AvocodePlugin: normal scale
AvocodePlugin: layer 76 (D8589CD3-3B56-421B-8014-1F339F0A1CE2)
AvocodePlugin: normal scale
AvocodePlugin: layer 77 (2EF4DD14-BDC8-40F1-A84E-C33E7FCC17EA)
AvocodePlugin: normal scale
AvocodePlugin: layer 78 (85C21D0D-51B0-4E6C-AF8C-D4872E4065BA)
AvocodePlugin: layer 0 (F4023B2B-3FA5-4AC6-A175-7EC260770A76)
AvocodePlugin: normal scale
AvocodePlugin: layer 1 (3C6CBB97-987F-4F6C-9E9F-6E5771C6E037)
AvocodePlugin: normal scale
AvocodePlugin: layer 2 (EAA40CA4-E97F-4BEB-B99F-3F7EE4093846)
AvocodePlugin: normal scale
AvocodePlugin: layer 79 (F530F8FB-EAE4-416B-A13B-D57498188E54)
AvocodePlugin: normal scale
AvocodePlugin: layer 80 (93D79350-8F13-4ED9-B28C-F06FC8CD89B3)
AvocodePlugin: normal scale
AvocodePlugin: layer 81 (D61B5DCD-2A05-47C2-B529-79D04121DD58)
AvocodePlugin: normal scale
AvocodePlugin: layer 82 (95765A23-A349-4064-AE2C-47A4F49134B0)
AvocodePlugin: layer 0 (41D52AB0-AC79-46A6-A745-68A97359E06C)
AvocodePlugin: normal scale
AvocodePlugin: layer 1 (82BFFBAB-9C05-45E9-BF63-026934B734C6)
AvocodePlugin: normal scale
AvocodePlugin: layer 2 (19C6015E-53AE-4E1C-8F34-BCA9734AE4F0)
AvocodePlugin: normal scale
AvocodePlugin: layer 3 (0B68AE48-5B4D-4603-9295-91C68D30F2EB)
AvocodePlugin: layer 0 (04094923-1A1A-4061-ADBA-784F3712258B)
AvocodePlugin: normal scale
AvocodePlugin: layer 1 (D80574F6-3EE8-46DA-922B-422396E9704B)
AvocodePlugin: layer 0 (356E925C-C401-4ACF-B3FA-3F41C364F842)
AvocodePlugin: normal scale
AvocodePlugin: layer 1 (B7EF62ED-CB16-47E7-A902-1F31D58FD7A7)
AvocodePlugin: normal scale
    - received data, parsing
    - parsed
    - done
page 2/4
artboard 1/1
page 3/4
artboard 1/7
artboard 2/7
artboard 3/7
artboard 4/7
artboard 5/7
artboard 6/7
artboard 7/7
page 4/4
artboard 1/3
artboard 2/3
artboard 3/3
artboard sync coscript result null
progress { maxPhase: 3,
  currentPhase: 1,
  phaseProgress: 0,
  completed: false,
  failed: false }
progress { maxPhase: 3,
  currentPhase: 1,
  phaseProgress: 0.5,
  completed: false,
  failed: false }
requested revision
[api] POST https://manager.avocode.com/api/extension/revisions/
revision with parent null
progress { maxPhase: 3,
  currentPhase: 2,
  phaseProgress: 0,
  completed: false,
  failed: false }
process images
process images with image processor

**Comment by bolekkerous** [comment]
As to why that happens - it's happening because the design is too complex - that means there are too much layers. Because of that, the plugin isn't able to retrieve correctly all the layer data (there are too many layers and because the layers are being processed locally at your computer at the moment, the RAM can't handle the load).

The thing that can solve this issue is to combine path layers which are going to be exported as a one layer with Layer -> Combine -> Union - this will create a single layer out of them that should export quicker. That way, the plugin just processes the combined shape and not all the layers.

If all your files use such patterns made of large amount of vector path layers, please consider combining them before exporting. This issue will not exist as soon as we implement the direct uploading of Sketch files and processing on our side.

We do apologize for the inconvenience.

**Comment by connor-bean** [comment]
Hey this is now fixed in 2.14.3. Please update your app
