### ISSUE TITLE
Avocode Plugin 3.5 Doesn't work in sketch 3.8.2

### ISSUE THREAD

**Issue by Paul2025** [avocode/avocode#881]
Hi. 

When I run the plugin, this open safari stays and goes about: blank. And nothing else happens.

**Comment by bolekkerous** [comment]
Hello,

We were able to come up with workaround for the time being. Please use this link once you see the "about: blank" page:

http://media.avocode.com/sketch/loader.html?url=http://127.0.0.1:33162

We apologize for any frustration this is causing.

Since this is a duplicate issue, I'll close this one. You can see the progress in #879.

Thanks,
Bolek, Avocode Team
