### ISSUE TITLE
Infinite exporting smart objects

### ISSUE THREAD

**Issue by maximhoffman** [avocode/avocode#91]
Hi, i have a psd file, ~9Mb, and I try to sync with Avocode. One exporting finished, but exporting Smart Objects doing infinity, without any progress information. I don't know why and what happened.

**Comment by marekhrabe** [comment]
Hi, sorry for the waiting without response. This is unfortunately error that came with Photoshop 2014.2.2 that we can't really fix on our side and we need Photoshop team to work on it. (You can see the issue here: https://github.com/adobe-photoshop/generator-core/issues/285)

Until new version of Photoshop comes, we will release a version of extension that skips exporting the contents of Smart Objects if they are inaccessible for us (only in 2014.2.2). They will be visible in design just like before, but they won't be inspectable in Avocode app. I will release that hot-fixed version in 24 hours

**Comment by conhuynh** [comment]
@marekhrabe excellent work! Thanks for the update, and good luck with the rest of the build!

**Comment by marekhrabe** [comment]
Sorry for the delay on my side. New extension is now live (it is `0.9.3`) - you can download and install the extension from https://madebysource.com/

I'm closing this for now, feel free to create separate issue if you still have problems with some designs
