### ISSUE TITLE
Rasterizes Sketch drawings

### ISSUE THREAD

**Issue by markst** [avocode/avocode#932]
Similar issue to #80 

All drawings are rasterized which prevents being able to export as SVG or @2x/3x/4x

**Comment by markst** [comment]
Avocode is treating all my shape layers as 'Rasterized Layer's

![image](https://cloud.githubusercontent.com/assets/274318/16149694/6d6c2726-348a-11e6-9148-89e64aae27b3.png)

![image](https://cloud.githubusercontent.com/assets/274318/16149696/74f20bc8-348a-11e6-9f97-ecc3c237ffe0.png)

**Comment by vojtatranta** [comment]
Hi @markst,
thank you for this report. Are you sure that this camera is a shape?

Can you send us this problematic .psd at team@avocode.com?

**Comment by markst** [comment]
@vojtatranta absolutely sure

<img width="704" alt="screen shot 2016-06-17 at 12 56 25" src="https://cloud.githubusercontent.com/assets/274318/16149837/4aff43f2-348b-11e6-93cd-1f2200f1d17d.png">

**Comment by vojtatranta** [comment]
@markst then send us please that psd so that we could examine it.

**Comment by markst** [comment]
@vojtatranta done

**Comment by bolekkerous** [comment]
Hello, @markst,

this is happening because the camera is a symbol. We're aware that the new symbols are viewed in Avocode as rasterized images and we're already working on a solution.

I'll close this one since it's a duplicate, you can follow the progress on the original issue #845 

Best regards,
Bolek, Avocode Team
