### ISSUE TITLE
Synched Sketch Files Appearing as White Canvases in Avocode App 

### ISSUE THREAD

**Issue by LindseyLeanne** [avocode/avocode#990]
I've synched about 8 different Art Boards to Avocode. When I try to inspect and open each artboard in Avocode, it appears as a white canvas. Elements are selectable, but nothing is visible...making it very difficult to code a design I can't see. 

Is this a common problem? Is there a known solution? The app is unusable at the moment. This issue has been occurring over the past 3-5 days each time I try to open a project. 

<img width="1079" alt="screen shot 2016-07-25 at 8 22 40 am" src="https://cloud.githubusercontent.com/assets/4657185/17101162/f9d550a6-5240-11e6-9bf9-2265184df1f7.png">

**Comment by connor-bean** [comment]
Hey, @LindseyLeanne -

Are you using the Sketch plugin to sync files? If so, which version of the plugin are you using? Last week, we released Sketch plugin 3.8 which supports Sketch version 3.9.

[You can download it here](https://github.com/avocode/avocode/blob/master/sketch-plugin.md)

Let us know if this issue isn't solved once you confirm you're using the newest version of the Sketch plugin.

Thanks,
Connor, Avocode Support

**Comment by danielmarquespt** [comment]
I am also experience the same issue. I am using the 3.8 Plugin.

**Comment by connor-bean** [comment]
Hey @danielmarquespt -

Can you send us the sketch logs and the problematic design to team@avocode.com? 

Here is a guide on how to get log files (it is the last paragraph) - https://github.com/avocode/avocode/blob/master/sketch-plugin.md#reporting-bugs

Thanks,
Connor, Avocode Support

**Comment by PMarcL** [comment]
I am also experiencing this issue. I'm on Windows 8. I don't have any plugin installed.

**Comment by connor-bean** [comment]
Hey @PMarcL -

Did someone else upload these designs for you using the Sketch plugin?
This issue is caused by using Sketch 3.9 version with older version of Sketch plugin.

Are you sure you are using the latest Sketch plugin (3.8 version)?

If the result is the same (white layers), please uninstall the plugin, quit Sketch and install the plugin again. After you sync the design again, it should work just fine.

Let me know whether it works!
Best regards,
Connor, Avocode Team

**Comment by connor-bean** [comment]
This issue is caused when someone who synced a design had an old Sketch extension but was using the new Sketch app version (3.9)

The solution for this is to re-upload the designs with the new extension (Sketch Plugin 3.8). You can download the newest plugin [here](https://manager.avocode.com/downloads/).

**Comment by PMarcL** [comment]
Thanks, this fix worked for me.
