### ISSUE TITLE
Uploads are blank when importing from Sketch

### ISSUE THREAD

**Issue by tibbyyo** [avocode/avocode#993]
After this last update, everything I import from Sketch syncs as a blank white screen, though I can still hover over each element. Avocode 2.8.4. Sketch plugin 3.8.
![screen shot 2016-07-26 at 8 42 18 am](https://cloud.githubusercontent.com/assets/407336/17144801/e2d85818-530c-11e6-8d72-3f7b6090ccd1.png)

**Comment by connor-bean** [comment]
Hey @tibbyyo -

Thanks for the report. It's the same as #990.

This issue is caused when someone who synced a design had an old Sketch extension but was using the new Sketch app version (3.9).

The solution for this is to re-upload the designs with the new extension (Sketch Plugin 3.8). You can download the newest plugin [here](https://manager.avocode.com/downloads/). 

Let me know if you still have issues once you have re-uploaded the designs with the new extension.

Thanks,
Connor, Avocode Support

**Comment by tibbyyo** [comment]
Ah. I couldn't find if someone else had the same problem. Thanks!
