### ISSUE TITLE
On opening design it shows a white blank screen

### ISSUE THREAD

**Issue by taher435** [avocode/avocode#994]
I can see the designs on manager.avocode.com and can also see the thumbnail preview on the Project tab. But when I open the designs, it just shows a white blank screen.

Screen shot - https://cldup.com/s1nJcIqoxR.png

Avocode version 2.8.4

**Comment by connor-bean** [comment]
Hey @taher435 -

This issue is caused when someone who synced a design had an old Sketch extension but was using the new Sketch app version (3.9)

The solution for this is to re-upload the designs with the new extension (Sketch Plugin 3.8). You can download the newest plugin [here](https://manager.avocode.com/downloads/).

Please close out of Sketch and reopen it before you try to sync any designs again.

Closing this ticket as it is the same as #990.
