### ISSUE TITLE
Elements not rendering in application view

### ISSUE THREAD

**Issue by Paul-Barnett** [avocode/avocode#998]
When opening designs recently uploaded from sketch in the desktop application they just show as a blank canvas. Mousing over and selecting elements of the design still shows there properties on the right, so they have obviously loaded in, but they're not visible.

![avocode_bug](https://cloud.githubusercontent.com/assets/8024618/17207190/3f37830a-54ab-11e6-9c45-19ec54bf5395.PNG)

Both the online version and the revision preview within the desktop app are still rendering correctly

Cheers,
Paul

**Comment by connor-bean** [comment]
Hello @Paul-Barnett 

This issue is caused by using Sketch 3.9 version with older version of Sketch plugin.

Are you sure you are using the latest Sketch plugin (3.8 version)?

If the result is the same (white layers), please uninstall the plugin, quit Sketch and install the plugin again. After you sync the design again with the new version (it's needed to resync it to see the difference), it should work just fine.

Let me know whether it works!
Best regards,
Connor, Avocode Team

**Comment by Paul-Barnett** [comment]
That's fixed it, thanks
